package com.csnexus.app.feature.tutor.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.csnexus.app.core.error.userMessage
import com.csnexus.app.core.network.ApiResult
import com.csnexus.app.feature.tutor.data.SimilarQuestionDto
import com.csnexus.app.feature.tutor.data.TutorAction
import com.csnexus.app.feature.tutor.data.TutorRepositoryContract
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

// ── UI state ──────────────────────────────────────────────────────────────────

/**
 * Represents the result area shown beneath the action buttons.
 * Only one variant is shown at a time; null means no result yet.
 */
sealed interface TutorResult {
    /** Plain text from explain / simplify / hint. */
    data class Text(val text: String) : TutorResult

    /** Ordered list of steps from the step-by-step action. */
    data class Steps(val steps: List<String>) : TutorResult

    /** A similar practice question generated by the backend. */
    data class Similar(val dto: SimilarQuestionDto) : TutorResult

    /** A failed send that can be retried. */
    data class FailedSend(val message: String, val retryLabel: String) : TutorResult
}

data class TutorUiState(
    /** Current question ID entered by the user (as raw string so field stays editable). */
    val questionIdInput: String = "",
    /** Selected answer the user entered (optional, passed as context to the backend). */
    val selectedAnswerInput: String = "",
    /** True while a backend request is in flight. */
    val loading: Boolean = false,
    /** Result to display below the action buttons; null = waiting for first action. */
    val result: TutorResult? = null,
    /** Interaction ID returned with the last successful response. Used for rating. */
    val interactionId: Int? = null,
    /** Transient feedback shown after a rating is submitted. */
    val ratingFeedback: String? = null,
    /** Pending offline message draft (unsent tutor message). Never rendered as a real response. */
    val offlineDraft: String? = null,
)

// ── ViewModel ─────────────────────────────────────────────────────────────────

class TutorViewModel(private val repository: TutorRepositoryContract) : ViewModel() {

    private val _uiState = MutableStateFlow(TutorUiState())
    val uiState: StateFlow<TutorUiState> = _uiState.asStateFlow()

    private var activeJob: Job? = null

    // ── Input field updates ───────────────────────────────────────────────────

    fun onQuestionIdChanged(value: String) {
        _uiState.update { it.copy(questionIdInput = value.filter(Char::isDigit).take(9)) }
    }

    fun onSelectedAnswerChanged(value: String) {
        _uiState.update { it.copy(selectedAnswerInput = value) }
    }

    // ── Action dispatch ───────────────────────────────────────────────────────

    /**
     * Fire one of the named tutor actions (explain / simplify / hint).
     * Cancels any in-flight request before starting a new one.
     */
    fun requestAction(action: TutorAction) {
        val questionId = _uiState.value.questionIdInput.toIntOrNull() ?: return
        val selected = _uiState.value.selectedAnswerInput.takeIf { it.isNotBlank() }
        dispatch {
            when (val result = repository.tutorAction(action, questionId, selected)) {
                is ApiResult.Success -> {
                    val dto = result.value
                    _uiState.update {
                        it.copy(
                            loading = false,
                            result = TutorResult.Text(dto.resolvedText()),
                            interactionId = dto.interactionId.takeIf { id -> id != 0 },
                            ratingFeedback = null,
                        )
                    }
                }
                is ApiResult.Failure -> reportSendFailure(action.label, result.error.userMessage())
            }
        }
    }

    /** Fire the step-by-step action. */
    fun requestStepByStep() {
        val questionId = _uiState.value.questionIdInput.toIntOrNull() ?: return
        val selected = _uiState.value.selectedAnswerInput.takeIf { it.isNotBlank() }
        dispatch {
            when (val result = repository.stepByStep(questionId, selected)) {
                is ApiResult.Success -> {
                    val dto = result.value
                    _uiState.update {
                        it.copy(
                            loading = false,
                            result = TutorResult.Steps(dto.steps),
                            interactionId = dto.interactionId.takeIf { id -> id != 0 },
                            ratingFeedback = null,
                        )
                    }
                }
                is ApiResult.Failure -> reportSendFailure("Step-by-step", result.error.userMessage())
            }
        }
    }

    /** Fire the similar question action. */
    fun requestSimilar() {
        val questionId = _uiState.value.questionIdInput.toIntOrNull() ?: return
        val selected = _uiState.value.selectedAnswerInput.takeIf { it.isNotBlank() }
        dispatch {
            when (val result = repository.similar(questionId, selected)) {
                is ApiResult.Success -> {
                    val dto = result.value
                    _uiState.update {
                        it.copy(
                            loading = false,
                            result = TutorResult.Similar(dto),
                            interactionId = dto.interactionId.takeIf { id -> id != 0 },
                            ratingFeedback = null,
                        )
                    }
                }
                is ApiResult.Failure -> reportSendFailure("Similar", result.error.userMessage())
            }
        }
    }

    /** Retry the last failed send — reads current inputs and last action type from result state. */
    fun retryLastAction() {
        val failed = _uiState.value.result as? TutorResult.FailedSend ?: return
        // Map the stored label back to an action or special command
        when (failed.retryLabel) {
            "Step-by-step" -> requestStepByStep()
            "Similar" -> requestSimilar()
            else -> {
                val action = TutorAction.actionValues.firstOrNull { it.label == failed.retryLabel }
                    ?: TutorAction.Explain
                requestAction(action)
            }
        }
    }

    // ── Rating ────────────────────────────────────────────────────────────────

    /**
     * Rate the last interaction. Fails silently, but shows transient feedback in the UI
     * (mirrors the web app: rating errors are swallowed, success shows brief confirmation).
     */
    fun rateInteraction(helpful: Boolean) {
        val interactionId = _uiState.value.interactionId ?: return
        viewModelScope.launch {
            repository.rateInteraction(interactionId, helpful)
            _uiState.update { it.copy(ratingFeedback = if (helpful) "Thanks for the thumbs up!" else "Got it, we'll improve.") }
        }
    }

    fun clearRatingFeedback() {
        _uiState.update { it.copy(ratingFeedback = null) }
    }

    // ── Offline draft ─────────────────────────────────────────────────────────

    /** Save an unsent message draft for offline situations. */
    fun saveOfflineDraft(message: String) {
        _uiState.update { it.copy(offlineDraft = message.takeIf { m -> m.isNotBlank() }) }
    }

    fun clearOfflineDraft() {
        _uiState.update { it.copy(offlineDraft = null) }
    }

    // ── Reset ─────────────────────────────────────────────────────────────────

    /** Clear all results and inputs to start a fresh conversation. */
    fun reset() {
        activeJob?.cancel()
        _uiState.update { TutorUiState() }
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    private fun dispatch(block: suspend () -> Unit) {
        activeJob?.cancel()
        _uiState.update { it.copy(loading = true, result = null, ratingFeedback = null) }
        activeJob = viewModelScope.launch { block() }
    }

    private fun reportSendFailure(actionLabel: String, message: String) {
        _uiState.update {
            it.copy(
                loading = false,
                result = TutorResult.FailedSend(
                    message = "Could not get a response: $message",
                    retryLabel = actionLabel,
                ),
                interactionId = null,
            )
        }
    }
}
