"""
Additional context clue questions to fill remaining placeholders.
Run gen_context_clues_questions.py after adding these to the main script.
"""

# 1 more Easy question
easy_fill = [
    ("The employees were motivated to work harder after receiving recognition. What does 'motivated' mean?",
     ["discouraged", "given a reason to act or try harder", "confused", "tired"], "given a reason to act or try harder",
     "Recognition would encourage harder work. 'Motivated' = given a reason to try harder.",
     ["context clues", "inference clue"]),
]

# 42 more Medium questions
medium_fill = [
    ("The agency was once proactive, but it has become complacent and satisfied with the status quo. What does 'complacent' mean?",
     ["ambitious", "smugly satisfied and unwilling to improve", "innovative", "stressed"], "smugly satisfied and unwilling to improve",
     "'But' contrasts 'proactive' with 'complacent.' Complacent = smugly satisfied.",
     ["context clues", "antonym clue"]),
    ("The senator's constituency includes farmers, fisherfolk, and small business owners. What does 'constituency' mean?",
     ["political party", "group of voters represented by an elected official", "government office", "campaign team"], "group of voters represented by an elected official",
     "'Includes' lists groups the senator represents, defining 'constituency.'",
     ["context clues", "example clue"]),
    ("The agency's autonomy was curtailed when the executive branch began requiring approval for all decisions. What does 'curtailed' mean?",
     ["expanded", "reduced or restricted", "maintained", "celebrated"], "reduced or restricted",
     "Requiring approval = less independence. 'Curtailed' = reduced.",
     ["context clues", "inference clue"]),
    ("Locus standi, or legal standing, determines whether a party has the right to bring a case to court. What does 'locus standi' mean?",
     ["location of court", "legal right to bring a case", "judge's decision", "court schedule"], "legal right to bring a case",
     "'Or legal standing' directly defines 'locus standi.'",
     ["context clues", "definition clue"]),
    ("The director was imperious; likewise, staff described her as domineering and expecting obedience. What does 'imperious' mean?",
     ["humble", "domineering and expecting obedience", "kind", "efficient"], "domineering and expecting obedience",
     "'Likewise' signals a synonym. 'Domineering and expecting obedience' equals 'imperious.'",
     ["context clues", "synonym clue"]),
    ("The old system was opaque and secretive, whereas the reformed process is transparent. What does 'opaque' mean?",
     ["clear", "not transparent; hidden from view", "efficient", "expensive"], "not transparent; hidden from view",
     "'Whereas' contrasts 'opaque' with 'transparent.' Opaque = not transparent.",
     ["context clues", "antonym clue"]),
    ("The government's fiscal tools include taxation, public borrowing, and expenditure management. What does 'fiscal tools' mean?",
     ["physical equipment", "financial instruments used by government", "military weapons", "communication devices"], "financial instruments used by government",
     "'Include' lists financial mechanisms, defining 'fiscal tools.'",
     ["context clues", "example clue"]),
    ("The reform's momentum dissipated after its chief advocate was transferred and no successor emerged. What does 'dissipated' mean?",
     ["increased", "gradually disappeared or scattered", "stabilized", "doubled"], "gradually disappeared or scattered",
     "Losing the advocate with no replacement = momentum fading. 'Dissipated' = gradually disappeared.",
     ["context clues", "inference clue"]),
    ("Writ of mandamus — a court order compelling an official to perform a duty — was filed against the mayor. What does 'writ of mandamus' mean?",
     ["arrest warrant", "court order to force an official to act", "search warrant", "subpoena"], "court order to force an official to act",
     "The dash phrase defines it as a court order compelling an official to perform a duty.",
     ["context clues", "definition clue"]),
    ("The negotiator was implacable; similarly, her opponents found her impossible to appease. What does 'implacable' mean?",
     ["agreeable", "unable to be appeased or pacified", "emotional", "confused"], "unable to be appeased or pacified",
     "'Similarly' signals a synonym. 'Impossible to appease' equals 'implacable.'",
     ["context clues", "synonym clue"]),
    ("The previous administration was interventionist, but the new government favors a laissez-faire approach. What does 'laissez-faire' mean?",
     ["controlling", "allowing things to happen without interference", "aggressive", "secretive"], "allowing things to happen without interference",
     "'But' contrasts 'interventionist' with 'laissez-faire.' Laissez-faire = non-interference.",
     ["context clues", "antonym clue"]),
    ("The agency's deliverables for the quarter include a revised manual, training modules, and a monitoring report. What does 'deliverables' mean?",
     ["promises", "tangible outputs expected to be produced", "meetings", "budgets"], "tangible outputs expected to be produced",
     "'Include' lists expected outputs, defining 'deliverables.'",
     ["context clues", "example clue"]),
    ("The official's hubris led to his downfall — his excessive pride blinded him to warnings. What does 'hubris' mean?",
     ["humility", "excessive pride or arrogance", "intelligence", "caution"], "excessive pride or arrogance",
     "Excessive pride blinding him to warnings = arrogance causing failure.",
     ["context clues", "inference clue"]),
    ("Quo warranto, meaning 'by what authority,' challenges a person's right to hold public office. What does 'quo warranto' mean?",
     ["resignation letter", "legal challenge to someone's right to hold office", "appointment letter", "election protest"], "legal challenge to someone's right to hold office",
     "'Meaning' defines quo warranto as challenging the right to hold office.",
     ["context clues", "definition clue"]),
    ("The spokesperson was equivocal; in the same way, journalists complained her statements were deliberately ambiguous. What does 'equivocal' mean?",
     ["clear", "deliberately ambiguous or unclear", "honest", "brief"], "deliberately ambiguous or unclear",
     "'In the same way' signals a synonym. 'Deliberately ambiguous' equals 'equivocal.'",
     ["context clues", "synonym clue"]),
    ("The agency was once nimble, but bureaucratic growth has made it ponderous and slow to respond. What does 'ponderous' mean?",
     ["agile", "slow and heavy; lacking agility", "efficient", "small"], "slow and heavy; lacking agility",
     "'But' contrasts 'nimble' with 'ponderous.' Ponderous = slow and heavy.",
     ["context clues", "antonym clue"]),
    ("The commission's investigative powers include summoning witnesses, requiring documents, and conducting inspections. What does 'investigative powers' mean?",
     ["legislative authority", "legal abilities to examine and gather evidence", "executive privilege", "judicial immunity"], "legal abilities to examine and gather evidence",
     "'Include' lists evidence-gathering activities, defining 'investigative powers.'",
     ["context clues", "example clue"]),
    ("The policy's unintended consequences became apparent only months later when businesses began closing. What does 'unintended consequences' mean?",
     ["planned results", "unexpected outcomes not originally foreseen", "benefits", "goals"], "unexpected outcomes not originally foreseen",
     "Becoming apparent only later + negative effects = unforeseen outcomes.",
     ["context clues", "inference clue"]),
    ("Certiorari — a writ by which a higher court reviews a lower court's decision — was granted by the Supreme Court. What does 'certiorari' mean?",
     ["final judgment", "higher court's review of a lower court decision", "arrest order", "bail hearing"], "higher court's review of a lower court decision",
     "The dash phrase defines certiorari as higher court reviewing lower court's decision.",
     ["context clues", "definition clue"]),
    ("The analyst was sagacious; likewise, her forecasts were described as wise and far-sighted. What does 'sagacious' mean?",
     ["foolish", "having keen judgment and foresight", "aggressive", "timid"], "having keen judgment and foresight",
     "'Likewise' signals a synonym. 'Wise and far-sighted' equals 'sagacious.'",
     ["context clues", "synonym clue"]),
    ("The old leadership was bellicose, whereas the new director prefers dialogue and peaceful resolution. What does 'bellicose' mean?",
     ["peaceful", "aggressive and eager to fight", "quiet", "diplomatic"], "aggressive and eager to fight",
     "'Whereas' contrasts 'bellicose' with 'dialogue and peaceful resolution.' Bellicose = aggressive.",
     ["context clues", "antonym clue"]),
    ("The agency's cross-cutting concerns include gender equality, environmental sustainability, and disability inclusion. What does 'cross-cutting concerns' mean?",
     ["minor issues", "themes that affect all areas of work", "budget items", "staff complaints"], "themes that affect all areas of work",
     "'Include' lists themes relevant across all programs, defining 'cross-cutting concerns.'",
     ["context clues", "example clue"]),
    ("The official's credibility was undermined when investigators discovered fabricated credentials. What does 'undermined' mean?",
     ["strengthened", "gradually weakened or damaged", "confirmed", "publicized"], "gradually weakened or damaged",
     "Fabricated credentials would damage trust. 'Undermined' = gradually weakened.",
     ["context clues", "inference clue"]),
    ("Devolution is defined as the transfer of powers from national to local government units. What does 'devolution' mean?",
     ["centralization", "transfer of power to local levels", "revolution", "evolution"], "transfer of power to local levels",
     "'Is defined as' directly defines devolution as transfer of powers to local units.",
     ["context clues", "definition clue"]),
    ("The policy was stringent; similarly, affected businesses described the regulations as strict and demanding. What does 'stringent' mean?",
     ["lenient", "strict and precisely defined", "vague", "optional"], "strict and precisely defined",
     "'Similarly' signals a synonym. 'Strict and demanding' equals 'stringent.'",
     ["context clues", "synonym clue"]),
    ("The new system was transparent, in stark contrast to the opaque processes that had hidden information. What does 'transparent' mean?",
     ["hidden", "open and clear to all", "complicated", "expensive"], "open and clear to all",
     "'In stark contrast to opaque' shows 'transparent' = open and clear.",
     ["context clues", "antonym clue"]),
    ("The commission exercises quasi-judicial functions, for example, hearing complaints and imposing penalties. What does 'quasi-judicial' mean?",
     ["purely legislative", "having some characteristics of a court", "advisory only", "ceremonial"], "having some characteristics of a court",
     "'For example' lists court-like functions, showing 'quasi-judicial' = having court characteristics.",
     ["context clues", "example clue"]),
    ("The department's morale plummeted after three consecutive budget cuts forced layoffs. What does 'plummeted' mean?",
     ["increased", "dropped sharply", "stabilized", "fluctuated"], "dropped sharply",
     "Budget cuts and layoffs would cause a sharp drop. 'Plummeted' = dropped sharply.",
     ["context clues", "inference clue"]),
    ("Fiduciary duty refers to the legal obligation to act in the best interest of another party. What does 'fiduciary' mean?",
     ["personal", "involving trust and responsibility for another", "financial", "optional"], "involving trust and responsibility for another",
     "'Refers to' defines fiduciary as involving obligation to act in another's best interest.",
     ["context clues", "definition clue"]),
    ("The administrator was judicious; likewise, her decisions were described as wise and well-considered. What does 'judicious' mean?",
     ["hasty", "showing good judgment", "biased", "emotional"], "showing good judgment",
     "'Likewise' signals a synonym. 'Wise and well-considered' equals 'judicious.'",
     ["context clues", "synonym clue"]),
    ("The agency's response was sluggish, whereas the private sector partner delivered results within days. What does 'sluggish' mean?",
     ["fast", "slow and lacking energy", "expensive", "innovative"], "slow and lacking energy",
     "'Whereas' contrasts 'sluggish' with delivering results quickly. Sluggish = slow.",
     ["context clues", "antonym clue"]),
    ("The anti-corruption campaign targeted various forms of graft, including kickbacks, bid rigging, and phantom projects. What does 'graft' mean?",
     ["hard work", "corrupt practices for personal gain", "charity", "investment"], "corrupt practices for personal gain",
     "'Including' lists corrupt practices, showing 'graft' = corruption for personal gain.",
     ["context clues", "example clue"]),
]

# 100 more Hard questions
hard_fill = [
    ("The senator's tendentious interpretation selected only supporting statistics while ignoring contradictory findings. What does 'tendentious' mean?",
     ["objective", "expressing a strong bias", "brief", "scientific"], "expressing a strong bias",
     "Selecting only supporting data + ignoring contradictions = biased.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's moribund reform program had not met in eighteen months, its budget zeroed out, and staff reassigned. What does 'moribund' mean?",
     ["thriving", "at the point of death or failure", "new", "controversial"], "at the point of death or failure",
     "No meetings + no budget + staff reassigned = effectively dead.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's parsimony with praise was legendary — in twenty years, no employee recalled receiving a compliment. What does 'parsimony' mean?",
     ["generosity", "extreme unwillingness to give", "enthusiasm", "fairness"], "extreme unwillingness to give",
     "Twenty years without a compliment = extreme stinginess.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's venality was an open secret — permits could be obtained faster with cash, and violations disappeared for the right price. What does 'venality' mean?",
     ["honesty", "willingness to be bribed", "efficiency", "strictness"], "willingness to be bribed",
     "Permits for cash + violations disappearing for money = corruption for money.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy debate descended into a maelstrom of competing interests, and the resulting chaos paralyzed decision-making. What does 'maelstrom' mean?",
     ["calm discussion", "situation of violent confusion", "compromise", "vote"], "situation of violent confusion",
     "Competing interests + chaos + paralysis = violent confusion.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's valedictory speech reflected on battles won and lost and expressed hope for successors. What does 'valedictory' mean?",
     ["inaugural", "serving as a farewell", "angry", "routine"], "serving as a farewell",
     "Reflecting on past + hoping successors continue = farewell speech.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigation's findings were damning but the committee's response was anemic — a mild statement and no referral for prosecution. What does 'anemic' mean?",
     ["strong", "lacking force or effectiveness", "illegal", "detailed"], "lacking force or effectiveness",
     "Mild statement + no prosecution = weak, lacking force.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's solipsistic management style treated the agency as an extension of herself — priorities shifted with her moods. What does 'solipsistic' mean?",
     ["collaborative", "excessively self-centered", "democratic", "efficient"], "excessively self-centered",
     "Agency as extension of herself + priorities shifting with moods = extreme self-centeredness.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's report exhibited studied neutrality that effectively condoned the behavior it documented by refusing to assign blame. What does 'condoned' mean?",
     ["condemned", "accepted without protest", "investigated", "publicized"], "accepted without protest",
     "Refusing to assign blame = allowing behavior to continue.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's culture of deference meant bad ideas from seniors went unchallenged — subordinates remained silent. What does 'deference' mean?",
     ["defiance", "respectful submission to a superior's judgment", "equality", "competition"], "respectful submission to a superior's judgment",
     "Bad ideas unchallenged + subordinates silent = submission to authority.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's apologia constructed an elaborate defense blaming external factors rather than acknowledging mistakes. What does 'apologia' mean?",
     ["apology", "formal defense of one's actions", "resignation", "confession"], "formal defense of one's actions",
     "Elaborate defense + blaming external factors = formal justification (not an apology).",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigation revealed the agency had become a fiefdom — the director treated resources as personal property and appointed loyalists. What does 'fiefdom' mean?",
     ["democracy", "domain controlled as private territory", "partnership", "corporation"], "domain controlled as private territory",
     "Resources as personal property + loyalists appointed = personal territory.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy's proponents displayed troubling certitude — dismissing all objections and treating assumptions as self-evident truths. What does 'certitude' mean?",
     ["doubt", "absolute certainty, especially unjustified", "curiosity", "flexibility"], "absolute certainty, especially unjustified",
     "Dismissing objections + treating assumptions as self-evident = unjustified certainty.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's deliberations were marked by acrimony — members interrupted each other and questioned motives. What does 'acrimony' mean?",
     ["harmony", "bitterness and ill feeling", "efficiency", "formality"], "bitterness and ill feeling",
     "Interrupting + questioning motives = bitter, hostile atmosphere.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's tenure was characterized by gradual arrogation of powers — absorbing functions and claiming jurisdictions without authorization. What does 'arrogation' mean?",
     ["delegation", "claiming or seizing without right", "reduction", "sharing"], "claiming or seizing without right",
     "Absorbing functions + claiming without authorization = seizing without right.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's response to the crisis was characterized by fatal torpor — officials held meetings about meetings while the situation deteriorated. What does 'torpor' mean?",
     ["urgency", "mental and physical inactivity", "efficiency", "panic"], "mental and physical inactivity",
     "Meetings about meetings while situation worsened = sluggish inactivity.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's speech was a masterpiece of litotes — saying the record was 'not entirely satisfactory' to convey devastating criticism. What does 'litotes' mean?",
     ["exaggeration", "understatement for emphasis", "repetition", "metaphor"], "understatement for emphasis",
     "'Not entirely satisfactory' conveying devastating criticism = understatement for effect.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's ukase restructured three divisions overnight without consultation — a unilateral decree. What does 'ukase' mean?",
     ["suggestion", "arbitrary authoritative decree", "resignation", "budget"], "arbitrary authoritative decree",
     "Without consultation + unilateral + overnight restructuring = arbitrary decree.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's philippic lasted ninety minutes — a sustained, blistering attack that spared no official from criticism. What does 'philippic' mean?",
     ["praise", "bitter verbal attack", "negotiation", "compromise"], "bitter verbal attack",
     "Sustained blistering attack + sparing no one = bitter verbal denunciation.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's pleonastic writing used five words where one would suffice and padded every paragraph with unnecessary qualifications. What does 'pleonastic' mean?",
     ["concise", "using more words than necessary", "elegant", "technical"], "using more words than necessary",
     "Five words where one suffices + padding paragraphs = using excess words.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigation's denouement came when a single document connected every thread and revealed the conspiracy. What does 'denouement' mean?",
     ["beginning", "final resolution or outcome", "complication", "delay"], "final resolution or outcome",
     "Single document revealing everything = the final resolution.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency head's suzerainty over regional offices was absolute — directors sought her approval for every decision. What does 'suzerainty' mean?",
     ["equality", "dominant control over others", "partnership", "independence"], "dominant control over others",
     "Seeking approval for every decision = dominant authority.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy debate devolved into logomachy — arguing about definitions while substantive issues remained unaddressed. What does 'logomachy' mean?",
     ["productive debate", "dispute about words rather than substance", "physical fight", "compromise"], "dispute about words rather than substance",
     "Arguing about definitions + substantive issues unaddressed = fighting over words.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's protean management style was collaborative one day and autocratic the next, making expectations impossible to predict. What does 'protean' mean?",
     ["consistent", "constantly changing", "weak", "aggressive"], "constantly changing",
     "Collaborative then autocratic + impossible to predict = constantly changing.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's Procrustean standardization forced every agency into the same template regardless of size or mission. What does 'Procrustean' mean?",
     ["flexible", "enforcing uniformity without regard for differences", "fair", "voluntary"], "enforcing uniformity without regard for differences",
     "Same template regardless of size/mission = enforcing uniformity.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's apothegm — 'Public service is a public trust' — became the unofficial motto of the reform movement. What does 'apothegm' mean?",
     ["long speech", "concise and memorable saying", "legal ruling", "campaign slogan"], "concise and memorable saying",
     "A short quoted phrase that became a motto = concise, memorable saying.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's legerdemain with budget figures concealed a deficit through creative accounting and reclassified expenditures. What does 'legerdemain' mean?",
     ["transparency", "skillful deception", "incompetence", "generosity"], "skillful deception",
     "Concealing deficit through creative accounting = skillful deception.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's sclerotic decision-making required seventeen signatures and nine months for routine expenditures. What does 'sclerotic' mean?",
     ["efficient", "rigid and unresponsive", "modern", "democratic"], "rigid and unresponsive",
     "17 signatures + 9 months for routine items = rigid, unable to function.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's Faustian bargain gave generous funding but required looking the other way when allies violated regulations. What does 'Faustian bargain' mean?",
     ["fair deal", "agreement sacrificing integrity for gain", "legal contract", "generous offer"], "agreement sacrificing integrity for gain",
     "Generous funding BUT ignoring violations = gaining by sacrificing principles.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's desultory oversight — sporadic meetings and cursory reviews — allowed problems to fester for years. What does 'desultory' mean?",
     ["systematic", "lacking a plan; random and unfocused", "aggressive", "thorough"], "lacking a plan; random and unfocused",
     "Sporadic + cursory + problems festering = random, unfocused.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's grandiloquent speeches were filled with elaborate metaphors but contained remarkably little substance. What does 'grandiloquent' mean?",
     ["simple", "pompous and extravagant in language", "brief", "factual"], "pompous and extravagant in language",
     "Elaborate metaphors + little substance = pompous language.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigation revealed a culture of omertà — no one spoke to investigators and documents disappeared overnight. What does 'omertà' mean?",
     ["transparency", "code of silence protecting wrongdoers", "cooperation", "efficiency"], "code of silence protecting wrongdoers",
     "No one spoke + disappearing documents = enforced silence.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy's architects displayed insouciance toward consequences — dismissing concerns and proceeding with breezy confidence. What does 'insouciance' mean?",
     ["concern", "casual lack of worry", "expertise", "hostility"], "casual lack of worry",
     "Dismissed concerns + breezy confidence = casual lack of worry.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's tenure was marked by gradual accretion of power — each small expansion went unchallenged until she controlled far beyond her mandate. What does 'accretion' mean?",
     ["loss", "gradual accumulation", "sudden seizure", "delegation"], "gradual accumulation",
     "Each small expansion building on the last = gradual accumulation.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's Delphic pronouncement could be interpreted as either approval or rejection depending on emphasis. What does 'Delphic' mean?",
     ["clear", "deliberately ambiguous", "angry", "lengthy"], "deliberately ambiguous",
     "Could be interpreted either way = deliberately ambiguous.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's schadenfreude was barely concealed — his thin smile revealed pleasure at his rival's project failure. What does 'schadenfreude' mean?",
     ["sympathy", "pleasure from another's misfortune", "anger", "indifference"], "pleasure from another's misfortune",
     "Thin smile + pleasure at rival's failure = enjoyment of another's misfortune.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's Potemkin reforms impressed visitors but changed nothing — new signage masked the same dysfunctional processes. What does 'Potemkin' mean?",
     ["genuine", "having a false appearance; a facade", "expensive", "modern"], "having a false appearance; a facade",
     "Impressed visitors but changed nothing + masking dysfunction = false appearance.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's encomium recounted the justice's landmark decisions and praised his intellectual rigor. What does 'encomium' mean?",
     ["criticism", "speech that praises highly", "eulogy for the dead", "legal brief"], "speech that praises highly",
     "Recounting achievements + praising rigor = high praise speech.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy debate reached an aporia — both sides presented logically valid but mutually exclusive arguments with no framework to resolve them. What does 'aporia' mean?",
     ["resolution", "irresolvable contradiction", "agreement", "deadline"], "irresolvable contradiction",
     "Logically valid but mutually exclusive + no resolution = irresolvable contradiction.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's quietus came from exhaustion — after twelve years of battles, she resigned with a one-sentence letter. What does 'quietus' mean?",
     ["promotion", "final end or settlement", "vacation", "transfer"], "final end or settlement",
     "Resignation after exhaustion + disappeared from public life = the final end.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The report was suffused with weary resignation — every recommendation hedged with caveats as though nothing would change. What does 'suffused' mean?",
     ["empty of", "spread throughout", "decorated with", "lacking"], "spread throughout",
     "Tone present in every recommendation = spread throughout.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's gambit — introducing an amendment she knew would fail to force opponents to vote publicly — was a calculated sacrifice. What does 'gambit' mean?",
     ["mistake", "strategic move involving sacrifice for advantage", "compromise", "retreat"], "strategic move involving sacrifice for advantage",
     "Introducing something she knew would fail to force opponents' hand = calculated sacrifice.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The findings were redolent of earlier scandals — the same patterns of cronyism and the same shell companies. What does 'redolent' mean?",
     ["different from", "strongly reminiscent of", "unrelated to", "worse than"], "strongly reminiscent of",
     "Same patterns + same companies as earlier = strongly reminiscent.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's sang-froid was remarkable — while others panicked, she methodically gathered facts and issued a measured response. What does 'sang-froid' mean?",
     ["panic", "composure in difficult situations", "anger", "indifference"], "composure in difficult situations",
     "Methodical while others panicked = composure under pressure.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's bowdlerized report removed references to officials, softened criticism, and replaced conclusions with bland observations. What does 'bowdlerized' mean?",
     ["expanded", "censored by removing sensitive content", "translated", "summarized"], "censored by removing sensitive content",
     "Removed references + softened criticism + replaced conclusions = censored.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The reform coalition proved ephemeral — united briefly by outrage, its members drifted back to competing agendas within weeks. What does 'ephemeral' mean?",
     ["permanent", "lasting a very short time", "powerful", "secretive"], "lasting a very short time",
     "United briefly + drifted within weeks = very short-lived.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's recalcitrance was legendary — she outlasted three secretaries and ignored countless directives. What does 'recalcitrance' mean?",
     ["cooperation", "stubborn resistance to authority", "efficiency", "innovation"], "stubborn resistance to authority",
     "Outlasting bosses + ignoring directives = stubborn resistance.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's dissimulation was masterful — every statement technically true yet collectively creating the opposite impression. What does 'dissimulation' mean?",
     ["honesty", "concealment of true intentions", "eloquence", "brevity"], "concealment of true intentions",
     "Technically true but creating opposite impression = hiding true meaning.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigator's perspicacity allowed her to detect patterns invisible to others and reveal the fraud network. What does 'perspicacity' mean?",
     ["confusion", "keen mental perception", "aggression", "patience"], "keen mental perception",
     "Detecting invisible patterns + connections others missed = keen perception.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy created a perverse incentive — rewarding case filing rather than resolution encouraged generating paperwork over solving problems. What does 'perverse incentive' mean?",
     ["positive motivation", "reward producing opposite of intended results", "financial bonus", "legal requirement"], "reward producing opposite of intended results",
     "Rewarding filing over resolving = encouraging wrong behavior.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's Machiavellian approach cultivated allies through favors and isolated rivals through rumor to maintain power. What does 'Machiavellian' mean?",
     ["honest", "cunning and unscrupulous in pursuing power", "democratic", "incompetent"], "cunning and unscrupulous in pursuing power",
     "Cultivating allies + isolating rivals + calculated ruthlessness = cunning power pursuit.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's Kafkaesque procedures trapped applicants in endless loops — each office referred them to another with no escape. What does 'Kafkaesque' mean?",
     ["efficient", "nightmarishly complex and illogical", "modern", "transparent"], "nightmarishly complex and illogical",
     "Endless loops + circular requirements + no escape = nightmarishly illogical.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's anodyne report avoided assigning blame or recommending action — saying nothing while appearing to say something. What does 'anodyne' mean?",
     ["controversial", "unlikely to offend; bland", "detailed", "accusatory"], "unlikely to offend; bland",
     "Avoiding blame + no action + saying nothing = deliberately inoffensive.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's cupidity led him to accept increasingly brazen bribes until the pattern became impossible to conceal. What does 'cupidity' mean?",
     ["generosity", "excessive greed for wealth", "stupidity", "ambition"], "excessive greed for wealth",
     "Insatiable greed + brazen bribes = excessive desire for money.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's jeremiad catalogued every failure and broken promise in a sustained two-hour denunciation. What does 'jeremiad' mean?",
     ["celebration", "prolonged lamentation or complaint", "brief remark", "legal argument"], "prolonged lamentation or complaint",
     "Two hours + cataloguing failures = prolonged complaint.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's ossified procedures still referenced defunct offices and specified typewriters — unchanged since 1985. What does 'ossified' mean?",
     ["flexible", "rigidly fixed and resistant to change", "modern", "efficient"], "rigidly fixed and resistant to change",
     "Unchanged since 1985 + defunct offices + typewriters = rigidly unchanged.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The prosecutor's forensic rhetoric wove evidence into a narrative so compelling that the verdict seemed inevitable. What does 'forensic rhetoric' mean?",
     ["scientific analysis", "persuasive argumentation for legal proceedings", "emotional outburst", "written report"], "persuasive argumentation for legal proceedings",
     "Evidence woven into compelling narrative + inevitable verdict = persuasive legal argumentation.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's probity was beyond question — thirty years without a single substantiated allegation of impropriety. What does 'probity' mean?",
     ["corruption", "strong moral integrity", "wealth", "popularity"], "strong moral integrity",
     "Thirty years + no allegations = unquestioned moral integrity.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy's proponents engaged in casuistry — elaborate arguments to justify what was simply a transfer of public resources to private interests. What does 'casuistry' mean?",
     ["honest reasoning", "specious reasoning to justify questionable acts", "scientific method", "legal precedent"], "specious reasoning to justify questionable acts",
     "Elaborate arguments to justify resource transfer = misleading reasoning.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency had become a sinecure — appointees drew salaries while performing no meaningful work, positions existing solely as rewards. What does 'sinecure' mean?",
     ["demanding job", "position with pay but no real duties", "volunteer role", "training program"], "position with pay but no real duties",
     "Drawing salaries + no meaningful work + rewards = jobs with pay but no duties.",
     ["context clues", "inference clue", "advanced vocabulary"]),
]

# 10 more medium questions
medium_fill_2 = [
    ("The reform effort stagnated because key legislators withdrew support and no new champions emerged. What does 'stagnated' mean?",
     ["accelerated", "ceased to develop or progress", "succeeded", "expanded"], "ceased to develop or progress",
     "Lost support + no new champions = no progress.",
     ["context clues", "inference clue"]),
    ("The senator's impassioned plea moved several undecided colleagues to vote in favor. What does 'impassioned' mean?",
     ["indifferent", "filled with strong emotion", "brief", "logical"], "filled with strong emotion",
     "Moving undecided people to act suggests strong emotion.",
     ["context clues", "inference clue"]),
    ("The policy change was precipitated by public scandals that made reform unavoidable. What does 'precipitated' mean?",
     ["prevented", "caused or brought about suddenly", "delayed", "predicted"], "caused or brought about suddenly",
     "Scandals making reform unavoidable = they caused the change.",
     ["context clues", "inference clue"]),
    ("Recidivism, which refers to the tendency of a criminal to reoffend, remains a justice system challenge. What does 'recidivism' mean?",
     ["rehabilitation", "tendency to commit crimes again", "imprisonment", "parole"], "tendency to commit crimes again",
     "'Which refers to' defines recidivism as the tendency to reoffend.",
     ["context clues", "definition clue"]),
    ("The negotiator was tenacious; in the same way, counterparts described her as persistent and unwilling to give up. What does 'tenacious' mean?",
     ["weak", "persistent and determined", "aggressive", "dishonest"], "persistent and determined",
     "'In the same way' signals a synonym. 'Persistent and unwilling to give up' equals 'tenacious.'",
     ["context clues", "synonym clue"]),
    ("The committee's decision was unanimous, whereas the previous vote had been deeply divided. What does 'unanimous' mean?",
     ["divided", "with complete agreement from all", "controversial", "delayed"], "with complete agreement from all",
     "'Whereas' contrasts 'unanimous' with 'deeply divided.'",
     ["context clues", "antonym clue"]),
    ("The training addressed soft skills, namely communication, emotional intelligence, and adaptability. What does 'soft skills' mean?",
     ["technical abilities", "interpersonal and social abilities", "physical skills", "computer skills"], "interpersonal and social abilities",
     "'Namely' lists interpersonal abilities, defining 'soft skills.'",
     ["context clues", "example clue"]),
    ("The mayor's pragmatic approach focused on immediate evacuation rather than debating long-term plans. What does 'pragmatic' mean?",
     ["theoretical", "practical and focused on results", "emotional", "political"], "practical and focused on results",
     "Focusing on immediate action rather than debate = practical.",
     ["context clues", "inference clue"]),
    ("Jurisprudence — the theory and philosophy of law — forms the foundation of the legal system. What does 'jurisprudence' mean?",
     ["criminal activity", "theory and philosophy of law", "police work", "legislation"], "theory and philosophy of law",
     "The dash phrase defines jurisprudence.",
     ["context clues", "definition clue"]),
    ("The new director was conciliatory and sought compromise, unlike her combative predecessor. What does 'conciliatory' mean?",
     ["aggressive", "intended to make peace", "indifferent", "secretive"], "intended to make peace",
     "'Unlike combative' contrasts with 'conciliatory.' Conciliatory = seeking peace.",
     ["context clues", "antonym clue"]),
]

# 40 more hard questions
hard_fill_2 = [
    ("The director's panegyric at the ceremony was so effusive that even the honoree appeared uncomfortable with the hyperbolic tributes. What does 'panegyric' mean?",
     ["criticism", "speech of elaborate praise", "resignation letter", "budget report"], "speech of elaborate praise",
     "Effusive praise + hyperbolic tributes = speech of elaborate praise.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's palliative measures addressed symptoms without touching root causes — temporary patches that changed nothing fundamental. What does 'palliative' mean?",
     ["curative", "relieving symptoms without addressing causes", "preventive", "destructive"], "relieving symptoms without addressing causes",
     "Addressing symptoms without root causes + temporary patches = relieving without curing.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's apostasy shocked her party — after fifteen years loyal, she crossed the floor and joined the opposition. What does 'apostasy' mean?",
     ["loyalty", "abandonment of a previously held allegiance", "promotion", "retirement"], "abandonment of a previously held allegiance",
     "Fifteen years loyal + crossed floor + joined opposition = abandoning allegiance.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's Sisyphean struggle against corruption seemed endless — each prosecution was followed by new schemes. What does 'Sisyphean' mean?",
     ["easy", "endlessly laborious and futile", "successful", "brief"], "endlessly laborious and futile",
     "Endless cycle + problem regenerating = labor that never achieves lasting results.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's solecism at the diplomatic reception — addressing the ambassador by the wrong title — created an awkward silence. What does 'solecism' mean?",
     ["compliment", "breach of etiquette or grammatical mistake", "achievement", "joke"], "breach of etiquette or grammatical mistake",
     "Wrong title + awkward silence at formal event = social error.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The report's turgid prose — bloated sentences and paragraphs circling without reaching a point — made it nearly unreadable. What does 'turgid' mean?",
     ["concise", "pompously inflated and difficult to read", "elegant", "factual"], "pompously inflated and difficult to read",
     "Bloated sentences + circling without point = inflated, unreadable.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's volubility was both asset and liability — speaking at length impressed constituents but exhausted colleagues. What does 'volubility' mean?",
     ["silence", "tendency to talk at great length", "wisdom", "anger"], "tendency to talk at great length",
     "Speaking at length + exhausting colleagues = excessive talkativeness.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's pusillanimous response — vague statements and deferred decisions — was condemned as cowardly. What does 'pusillanimous' mean?",
     ["brave", "showing a lack of courage", "aggressive", "efficient"], "showing a lack of courage",
     "Vague statements + deferred decisions + condemned as cowardly = lacking courage.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's Pyrrhic victory left her funded but politically isolated — she won the money but lost every ally. What does 'Pyrrhic victory' mean?",
     ["complete triumph", "victory so costly it equals defeat", "narrow loss", "compromise"], "victory so costly it equals defeat",
     "Won money but lost all allies = victory so costly it equals defeat.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's meretricious charm — all surface polish — concealed a calculating mind that exploited every interaction. What does 'meretricious' mean?",
     ["genuine", "superficially attractive but lacking value", "ugly", "modest"], "superficially attractive but lacking value",
     "Surface polish + concealing calculation = attractive on surface but valueless.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's atavistic management — rigid hierarchies and punishment-based motivation — belonged to a previous century. What does 'atavistic' mean?",
     ["modern", "reverting to something ancient", "efficient", "democratic"], "reverting to something ancient",
     "Rigid hierarchies + punishment-based + previous century = reverting to primitive.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The prosecutor's peroration distilled months of testimony into a single devastating conclusion delivered with quiet intensity. What does 'peroration' mean?",
     ["opening statement", "concluding part of a speech", "cross-examination", "objection"], "concluding part of a speech",
     "Final words + distilling into conclusion = concluding part of speech.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's tergiversation frustrated both sides — she supported the bill, then undermined it, then claimed neutrality. What does 'tergiversation' mean?",
     ["consistency", "evasion or changing of position", "honesty", "silence"], "evasion or changing of position",
     "Supported then undermined then claimed neutrality = repeatedly changing position.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's culture of impunity meant officials faced no consequences — complaints buried and investigations perfunctory. What does 'impunity' mean?",
     ["accountability", "exemption from punishment", "efficiency", "transparency"], "exemption from punishment",
     "No consequences + buried complaints + perfunctory investigations = freedom from punishment.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's palimpsest of competing agendas showed traces of earlier drafts with entirely different conclusions. What does 'palimpsest' mean?",
     ["original document", "something bearing traces of earlier forms", "blank page", "final version"], "something bearing traces of earlier forms",
     "Traces of earlier drafts + overwritten but not erased = bearing traces of earlier versions.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's nostalgia invoked an imagined past of perfect governance to criticize present realities that were actually improvements. What does 'nostalgia' mean?",
     ["anger", "sentimental longing for the past", "optimism", "indifference"], "sentimental longing for the past",
     "Invoking imagined past + golden age = sentimental longing.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy's architects were guilty of hubris — assuming perfection despite warnings and dismissing critics, only to watch the program collapse. What does 'hubris' mean?",
     ["humility", "excessive pride leading to downfall", "expertise", "caution"], "excessive pride leading to downfall",
     "Assumed perfection + ignored warnings + collapsed = excessive pride causing failure.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's rhetoric was suffused with nostalgia for a golden age that historical records show never actually existed. What does 'suffused' mean?",
     ["devoid of", "thoroughly filled or spread through", "decorated with", "lacking"], "thoroughly filled or spread through",
     "Rhetoric thoroughly filled with nostalgia = spread throughout.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigation revealed systematic peculation — public funds diverted into personal accounts through fictitious suppliers. What does 'peculation' mean?",
     ["investment", "embezzlement of public funds", "budgeting", "fundraising"], "embezzlement of public funds",
     "Public funds diverted to personal accounts = stealing public money.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's report was a masterpiece of obfuscation — dense jargon ensuring no one could determine what it recommended. What does 'obfuscation' mean?",
     ["clarity", "deliberate obscuring of meaning", "brevity", "accuracy"], "deliberate obscuring of meaning",
     "Dense jargon + no one could determine meaning = deliberately making unclear.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The whistleblower's allegations proved prescient — within six months every prediction came true. What does 'prescient' mean?",
     ["false", "having foreknowledge of events", "exaggerated", "irrelevant"], "having foreknowledge of events",
     "Every prediction coming true = she foresaw events.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's sycophantic behavior — excessive flattery and eager agreement — fooled no one about his true motives. What does 'sycophantic' mean?",
     ["defiant", "excessively flattering to gain advantage", "honest", "professional"], "excessively flattering to gain advantage",
     "Excessive flattery + eager agreement to gain favor = seeking advantage through flattery.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy architects displayed sangfroid under attack — calmly presenting data and answering hostile questions without emotion. What does 'sangfroid' mean?",
     ["panic", "composure under pressure", "anger", "confusion"], "composure under pressure",
     "Calmly presenting + answering without emotion under attack = coolness under pressure.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The investigation revealed a Byzantine web of shell companies designed to obscure true ownership. What does 'Byzantine' mean?",
     ["simple", "excessively complicated", "ancient", "religious"], "excessively complicated",
     "Shell companies + intermediaries designed to obscure = extremely complicated.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's erstwhile allies abandoned him as the scandal deepened — those who once championed his cause now distanced themselves. What does 'erstwhile' mean?",
     ["current", "former", "loyal", "powerful"], "former",
     "'Abandoned' + 'once championed' + 'now distanced' = they were former allies.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's endemic inefficiency had calcified into organizational culture that actively resisted improvement over decades. What does 'calcified' mean?",
     ["dissolved", "hardened into rigid unchangeable state", "improved", "spread"], "hardened into rigid unchangeable state",
     "Decades of problems becoming culture that resists change = hardened into rigidity.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The prosecutor's case was circumstantial — no witness saw the act, but accumulated forensic data created an overwhelming inference. What does 'circumstantial' mean?",
     ["direct", "based on inference rather than direct proof", "fabricated", "insufficient"], "based on inference rather than direct proof",
     "No witness but inference from accumulated evidence = based on inference, not direct proof.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's mendacity was exposed — years of fabricated reports and falsified credentials unraveled under scrutiny. What does 'mendacity' mean?",
     ["honesty", "habitual lying", "competence", "ambition"], "habitual lying",
     "Fabricated reports + falsified credentials = habitual dishonesty.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's imperious manner alienated subordinates — issuing commands without explanation and dismissing suggestions with contempt. What does 'imperious' mean?",
     ["humble", "domineering and overbearing", "efficient", "friendly"], "domineering and overbearing",
     "Commands without explanation + dismissing with contempt = domineering.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's speech was a tour de force of political dissimulation — technically true statements creating an impression opposite to reality. What does 'dissimulation' mean?",
     ["honesty", "concealment of true feelings", "eloquence", "brevity"], "concealment of true feelings",
     "Technically true but creating opposite impression = hiding true meaning.",
     ["context clues", "inference clue", "advanced vocabulary"]),
]

# Final 10 hard questions
hard_fill_3 = [
    ("The agency's response displayed a fatal insouciance — officials dismissed warnings with breezy confidence while the crisis deepened around them. What does 'insouciance' mean?",
     ["vigilance", "casual indifference to danger or concern", "expertise", "panic"], "casual indifference to danger or concern",
     "Dismissing warnings + breezy confidence while crisis deepened = casual indifference.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's polemic against the judiciary was relentless — a sustained, one-sided attack that offered no balanced assessment or constructive alternative. What does 'polemic' mean?",
     ["praise", "aggressive attack on a position or institution", "compromise", "analysis"], "aggressive attack on a position or institution",
     "Sustained one-sided attack + no balance + no alternative = aggressive attack.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The official's turpitude was eventually documented — a career-long pattern of dishonesty, self-dealing, and betrayal of public trust. What does 'turpitude' mean?",
     ["excellence", "depravity or wickedness", "competence", "ambition"], "depravity or wickedness",
     "Dishonesty + self-dealing + betrayal of trust = moral wickedness.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's report was a farrago of contradictions — asserting budget discipline while recommending massive spending, praising efficiency while adding layers of bureaucracy. What does 'farrago' mean?",
     ["model of clarity", "confused mixture of things", "brief summary", "legal document"], "confused mixture of things",
     "Contradictions + asserting opposites simultaneously = confused mixture.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's hegemony over the sector was unchallenged — no policy was adopted, no appointment made, and no budget approved without her explicit consent. What does 'hegemony' mean?",
     ["equality", "dominant influence or authority", "partnership", "absence"], "dominant influence or authority",
     "Nothing done without her consent = dominant, unchallenged authority.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The policy's detractors engaged in sophistry — arguments that sounded logical but relied on false premises and misleading analogies. What does 'sophistry' mean?",
     ["honest debate", "clever but misleading reasoning", "scientific proof", "emotional appeal"], "clever but misleading reasoning",
     "Sounded logical + false premises + misleading analogies = clever but misleading reasoning.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The senator's opprobrium fell heaviest on those who had promised reform but delivered nothing — her contempt for their hypocrisy was palpable. What does 'opprobrium' mean?",
     ["praise", "harsh criticism or public disgrace", "sympathy", "indifference"], "harsh criticism or public disgrace",
     "Contempt + targeting hypocrisy + heaviest criticism = harsh public criticism.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The agency's Byzantine procurement process required applicants to navigate fourteen offices, secure twenty-three signatures, and wait an average of eleven months. What does 'Byzantine' mean?",
     ["streamlined", "excessively complex and convoluted", "transparent", "modern"], "excessively complex and convoluted",
     "Fourteen offices + twenty-three signatures + eleven months = excessively complex.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The director's abnegation of responsibility was complete — she blamed subordinates, cited unclear guidelines, and insisted the failures occurred outside her purview. What does 'abnegation' mean?",
     ["acceptance", "renunciation or denial of responsibility", "celebration", "expansion"], "renunciation or denial of responsibility",
     "Blaming others + citing unclear guidelines + insisting outside her purview = denying responsibility.",
     ["context clues", "inference clue", "advanced vocabulary"]),
    ("The committee's findings revealed a pattern of systematic prevarication — officials had lied under oath, falsified timelines, and invented meetings that never occurred. What does 'prevarication' mean?",
     ["honesty", "deliberate evasion of truth; lying", "efficiency", "cooperation"], "deliberate evasion of truth; lying",
     "Lied under oath + falsified timelines + invented meetings = deliberate lying.",
     ["context clues", "inference clue", "advanced vocabulary"]),
]
