"""Additional spelling words to reach 200 per difficulty level."""

EASY_WORDS_4 = [
    ("accommodation", ["accomodation", "acomodation", "accommadation"],
     "Double 'c' and double 'm' — accommodate + ion.", ["double-letter"]),
    ("achievement", ["achevement", "achievment", "acheivement"],
     "Achieve + ment — 'ie' pattern retained.", ["ie-ei-rule", "suffix"]),
    ("administration", ["adminstration", "administracion", "administrasion"],
     "Contains '-istration' — administer → administration.", ["suffix"]),
    ("approximately", ["approximatly", "aproximately", "approximatley"],
     "Approximate + ly — double 'p.'", ["double-letter", "suffix"]),
    ("calculation", ["calculaton", "calulation", "calculasion"],
     "Contains '-tion' — calculate → calculation.", ["suffix"]),
    ("celebration", ["celebraton", "celabration", "celebrasion"],
     "Contains '-tion' — celebrate → celebration.", ["suffix"]),
    ("classification", ["classifcation", "classificaton", "clasification"],
     "Double 's' and '-tion' ending.", ["double-letter", "suffix"]),
    ("combination", ["combinaton", "combonation", "combinasion"],
     "Contains '-tion' — combine → combination.", ["suffix"]),
    ("comfortable", ["comfertable", "comftable", "comfertible"],
     "Contains '-fortable' — comfort + able.", ["suffix"]),
    ("commercial", ["comercial", "commerical", "commersial"],
     "Double 'm' and '-cial' ending.", ["double-letter", "suffix"]),
    ("communication", ["comunication", "communicaton", "comminication"],
     "Double 'm' and '-tion' ending.", ["double-letter", "suffix"]),
    ("competition", ["competion", "compitition", "competiton"],
     "Contains '-ition' — compete → competition.", ["suffix"]),
    ("concentration", ["concentraton", "consintration", "concentrasion"],
     "Contains '-tration' — concentrate → concentration.", ["suffix"]),
    ("confirmation", ["confirmaton", "confermation", "confirmasion"],
     "Contains '-tion' — confirm → confirmation.", ["suffix"]),
    ("consideration", ["consideraton", "considiration", "considerasion"],
     "Contains '-tion' — consider → consideration.", ["suffix"]),
    ("construction", ["constrution", "constructon", "construstion"],
     "Contains '-tion' — construct + ion.", ["suffix"]),
    ("contribution", ["contributon", "contrabution", "contributian"],
     "Contains '-tion' — contribute → contribution.", ["suffix"]),
    ("conversation", ["conversaton", "conversasion", "convorsation"],
     "Contains '-tion' — converse → conversation.", ["suffix"]),
    ("definition", ["defenition", "definision", "defintion"],
     "Contains '-ition' — define → definition.", ["suffix"]),
    ("demonstration", ["demonstraton", "demostration", "demonstrasion"],
     "Contains '-tion' — demonstrate → demonstration.", ["suffix"]),
    ("determination", ["determinaton", "detirmination", "determinasion"],
     "Contains '-ination' — determine → determination.", ["suffix"]),
    ("distribution", ["distribusion", "distributon", "distrabution"],
     "Contains '-tion' — distribute → distribution.", ["suffix"]),
    ("documentation", ["documentaton", "documantation", "documentasion"],
     "Contains '-tion' — document → documentation.", ["suffix"]),
    ("effectiveness", ["effectivness", "effectivenes", "efectiveness"],
     "Effective + ness — retains the 'e.'", ["suffix"]),
    ("establishment", ["establisment", "establishmant", "estableshment"],
     "Establish + ment — no letters dropped.", ["suffix"]),
    ("evaluation", ["evaluaton", "evalution", "evaluasion"],
     "Contains '-tion' — evaluate → evaluation.", ["suffix"]),
    ("examination", ["examinaton", "examenation", "examinasion"],
     "Contains '-tion' — examine → examination.", ["suffix"]),
    ("expectation", ["expectaton", "expactation", "expectasion"],
     "Contains '-tion' — expect → expectation.", ["suffix"]),
    ("explanation", ["explaination", "explanasion", "explination"],
     "No 'i' after 'expla-' — explain → explanation.", ["suffix"]),
    ("identification", ["identifcation", "identificaton", "identifacation"],
     "Contains '-ification' — identify → identification.", ["suffix"]),
    ("implementation", ["implimentation", "implementaton", "implemenation"],
     "Contains '-entation' — implement → implementation.", ["suffix"]),
    ("improvement", ["improvment", "improvemant", "improovement"],
     "Improve + ment — retains the 'e.'", ["suffix"]),
    ("information", ["informaton", "infomation", "informasion"],
     "Contains '-tion' — inform → information.", ["suffix"]),
    ("investigation", ["investigaton", "investagation", "investigasion"],
     "Contains '-tion' — investigate → investigation.", ["suffix"]),
    ("legislation", ["legislaton", "legeslation", "legislasion"],
     "Contains '-tion' — legislate → legislation.", ["suffix"]),
    ("maintenance", ["maintainance", "maintenence", "maintanance"],
     "Drops the 'i' from maintain — suffix is '-enance.'", ["suffix"]),
    ("measurement", ["measurment", "measuremant", "mesurement"],
     "Measure + ment — retains the 'e.'", ["suffix"]),
    ("negotiation", ["negotation", "negotiaton", "negoatiation"],
     "Contains '-tiation' — negotiate → negotiation.", ["suffix"]),
    ("observation", ["observaton", "observasion", "obsarvation"],
     "Contains '-tion' — observe → observation.", ["suffix"]),
    ("participation", ["participaton", "particapation", "participasion"],
     "Contains '-tion' — participate → participation.", ["suffix"]),
    ("presentation", ["presentaton", "presintation", "presentasion"],
     "Contains '-tion' — present → presentation.", ["suffix"]),
    ("professional", ["proffesional", "profesional", "proffessional"],
     "One 'f' and double 's' — profess + ional.", ["double-letter"]),
    ("recommendation", ["recomendation", "recommendaton", "reccommendation"],
     "One 'c' and double 'm' — recommend + ation.", ["double-letter"]),
    ("registration", ["registraton", "registeration", "regestration"],
     "Contains '-tration' — register → registration.", ["suffix"]),
    ("relationship", ["realtionship", "relationshp", "relashionship"],
     "Relation + ship — no letters dropped.", ["suffix"]),
    ("representative", ["representitive", "representetive", "representativ"],
     "Contains '-ative' — represent + ative.", ["suffix"]),
    ("responsibility", ["responsability", "responsibilty", "responsiblity"],
     "Contains '-ibility' — responsible → responsibility.", ["suffix"]),
    ("satisfaction", ["satisfation", "satisfacton", "satisfasion"],
     "Contains '-faction' — satisfy → satisfaction.", ["suffix"]),
    ("specification", ["specificaton", "specifacation", "specificasion"],
     "Contains '-ification' — specify → specification.", ["suffix"]),
    ("transportation", ["transportaton", "transportasion", "transpotation"],
     "Contains '-tion' — transport → transportation.", ["suffix"]),
]

MEDIUM_WORDS_4 = [
    ("absenteeism", ["absenteeizm", "absentiesm", "absenteism"],
     "Contains '-eeism' — absentee + ism.", ["suffix"]),
    ("acclimatize", ["aclimatize", "acclimatise", "acclimitize"],
     "Double 'c' — from Latin 'acclimare.'", ["double-letter", "latin-origin"]),
    ("adjudication", ["ajudication", "adjudicaton", "adjudacation"],
     "Contains 'adj-' and '-tion' ending.", ["latin-origin", "suffix"]),
    ("amalgamation", ["amalgamaton", "amalgimation", "amalgamashion"],
     "Contains '-tion' — amalgamate → amalgamation.", ["suffix"]),
    ("amelioration", ["amelioraton", "amilioration", "ameliorasion"],
     "Contains '-tion' — ameliorate → amelioration.", ["latin-origin", "suffix"]),
    ("annunciation", ["anunciation", "annunciaton", "annunsiation"],
     "Double 'n' and '-tion' ending.", ["double-letter", "suffix"]),
    ("appropriateness", ["appropriatness", "apropiateness", "appropriatenes"],
     "Appropriate + ness — retains the 'e.'", ["suffix"]),
    ("assassination", ["assasination", "assassinaton", "asassination"],
     "Four 's' letters and double 's' twice.", ["double-letter"]),
    ("authentication", ["authenticaton", "authentacation", "authentification"],
     "Contains '-tion' — authenticate → authentication.", ["suffix"]),
    ("capitalization", ["capitalizaton", "capitalisation", "capitilization"],
     "Contains '-ization' — capitalize → capitalization.", ["suffix"]),
    ("characterization", ["characterizaton", "charecterization", "characterisation"],
     "Contains '-ization' — characterize → characterization.", ["suffix"]),
    ("circumscription", ["circumscripton", "circunscription", "circumscripshion"],
     "Contains 'circum-' prefix — circumscribe → circumscription.", ["latin-origin"]),
    ("coagulation", ["coagulaton", "coagualation", "coagulasion"],
     "Contains '-tion' — coagulate → coagulation.", ["latin-origin", "suffix"]),
    ("collaboration", ["colaboration", "collaboraton", "collaberation"],
     "Double 'l' and '-tion' ending.", ["double-letter", "suffix"]),
    ("commemoration", ["comemoraton", "commemoraton", "comemmoration"],
     "Double 'm' in 'com + memor' — commemorate + ion.", ["double-letter"]),
    ("commensurable", ["comensurable", "commensureable", "commensurble"],
     "Double 'm' and '-able' ending.", ["double-letter", "suffix"]),
    ("communicable", ["comunicable", "communicible", "communicabel"],
     "Double 'm' and '-able' ending.", ["double-letter", "suffix"]),
    ("concatenation", ["concatination", "concatenaton", "concatanation"],
     "Contains '-ation' — concatenate → concatenation.", ["suffix"]),
    ("condescension", ["condescention", "condescenshion", "condecension"],
     "Contains '-sion' — condescend → condescension.", ["suffix"]),
    ("confiscation", ["confiscaton", "confiskation", "confiscasion"],
     "Contains '-tion' — confiscate → confiscation.", ["suffix"]),
    ("conglomeration", ["conglomeraton", "conglameration", "conglomerasion"],
     "Contains '-tion' — conglomerate → conglomeration.", ["suffix"]),
    ("conscription", ["conscripton", "conscripsion", "conscripshion"],
     "Contains '-tion' — conscript → conscription.", ["suffix"]),
    ("consolidation", ["consolidaton", "consoladation", "consolidasion"],
     "Contains '-tion' — consolidate → consolidation.", ["suffix"]),
    ("contamination", ["contaminaton", "contamanation", "contaminasion"],
     "Contains '-tion' — contaminate → contamination.", ["suffix"]),
    ("corroboration", ["coroboraton", "corroboraton", "coroboration"],
     "Double 'r' and '-tion' ending.", ["double-letter", "suffix"]),
    ("crystallization", ["crystalizaton", "crystallizaton", "cristallization"],
     "Double 'l' and '-ization' ending.", ["double-letter", "suffix"]),
    ("decentralization", ["decentralizaton", "desentralization", "decentralisation"],
     "Contains '-ization' — decentralize → decentralization.", ["suffix"]),
    ("decontamination", ["decontaminaton", "decontaminasion", "decontamation"],
     "Contains 'de-' prefix — decontaminate → decontamination.", ["prefix", "suffix"]),
    ("deliberation", ["deliberaton", "delibration", "deliberasion"],
     "Contains '-tion' — deliberate → deliberation.", ["suffix"]),
    ("denomination", ["denominaton", "denomanation", "denominasion"],
     "Contains '-tion' — denominate → denomination.", ["suffix"]),
    ("differentiation", ["differentiaton", "diferentiation", "differentiasion"],
     "Double 'f' and '-tion' ending.", ["double-letter", "suffix"]),
    ("disqualification", ["disqualificaton", "disqualifacation", "disqualifiction"],
     "Contains '-ification' — disqualify → disqualification.", ["suffix"]),
    ("dissatisfaction", ["disatisfaction", "dissatisfacton", "dissatisfasion"],
     "Double 's' — dis + satisfaction.", ["double-letter", "suffix"]),
    ("documentation", ["documentaton", "documantation", "documentasion"],
     "Contains '-tion' — document → documentation.", ["suffix"]),
    ("ecclesiastical", ["eclesiastical", "ecclesiasticle", "ecclasiastical"],
     "Double 'c' — from Greek 'ekklesia.'", ["double-letter", "greek-origin"]),
    ("electrification", ["electrificaton", "electrifacation", "electrifiction"],
     "Contains '-ification' — electrify → electrification.", ["suffix"]),
    ("embellishment", ["embelishment", "embellishmant", "embelishmant"],
     "Double 'l' — embellish + ment.", ["double-letter"]),
    ("encapsulation", ["encapsulaton", "incapsulation", "encapsulasion"],
     "Contains '-tion' — encapsulate → encapsulation.", ["suffix"]),
    ("entrepreneurship", ["entreprenuership", "entrepreneurshp", "entrepeneurship"],
     "From 'entrepreneur' + '-ship.'", ["french-origin"]),
    ("exacerbation", ["exacerbaton", "exaserbation", "exacerbashion"],
     "Contains '-tion' — exacerbate → exacerbation.", ["suffix"]),
    ("excommunication", ["excomunication", "excommunicaton", "excommuncation"],
     "Double 'm' and '-tion' ending.", ["double-letter", "suffix"]),
    ("exemplification", ["exemplificaton", "exemplifacation", "exemplifiction"],
     "Contains '-ification' — exemplify → exemplification.", ["suffix"]),
    ("experimentation", ["experimentaton", "expirementation", "experimentasion"],
     "Contains '-tion' — experiment → experimentation.", ["suffix"]),
    ("familiarization", ["familiarizaton", "familiarisation", "familarizaton"],
     "Contains '-ization' — familiarize → familiarization.", ["suffix"]),
    ("generalization", ["generalizaton", "generalisation", "generilization"],
     "Contains '-ization' — generalize → generalization.", ["suffix"]),
    ("hospitalization", ["hospitalizaton", "hospitalisation", "hospitilization"],
     "Contains '-ization' — hospitalize → hospitalization.", ["suffix"]),
    ("implementation", ["implementaton", "implimentation", "implemenation"],
     "Contains '-entation' — implement → implementation.", ["suffix"]),
    ("improvisation", ["improvisaton", "improvization", "improvasation"],
     "Contains '-tion' — improvise → improvisation.", ["suffix"]),
    ("incarceration", ["incarseraton", "incarceraton", "incarcerasion"],
     "Contains '-tion' — incarcerate → incarceration.", ["suffix"]),
    ("indemnification", ["indemnificaton", "indemnifacation", "indemnifiction"],
     "Contains '-ification' — indemnify → indemnification.", ["suffix"]),
]

HARD_WORDS_3 = [
    ("antediluvian", ["antediluvien", "antidiluvian", "antediluvain"],
     "Contains 'ante-' (before) + 'diluvian' (flood) — Latin origin.", ["latin-origin"]),
    ("apotheosis", ["apothiosis", "apotheoses", "apotheoisis"],
     "Contains '-theosis' — from Greek 'apotheosis.'", ["greek-origin"]),
    ("appurtenance", ["appurtenence", "apurtenance", "appurtenanse"],
     "Double 'p' and '-ance' ending — from Old French.", ["double-letter", "french-origin"]),
    ("archipelago", ["archepelago", "archipeligo", "archepilago"],
     "Contains '-ipelago' — from Greek 'archi' + 'pelagos.'", ["greek-origin"]),
    ("asphyxiation", ["asphixiation", "asphyxiaton", "asphixiaton"],
     "Contains 'phyx' — from Greek 'asphyxia.'", ["greek-origin"]),
    ("baccalaureate", ["bacalaureate", "baccalaureat", "baccaloreate"],
     "Double 'c' and '-eate' ending — from Latin 'baccalaureus.'", ["double-letter", "latin-origin"]),
    ("bellicose", ["belicose", "bellicoes", "bellicoss"],
     "Double 'l' — from Latin 'bellicosus.'", ["double-letter", "latin-origin"]),
    ("bibliophile", ["bibliophyle", "bibliofhile", "bibliophil"],
     "Contains '-phile' — from Greek 'biblion' + 'philos.'", ["greek-origin"]),
    ("cacophonous", ["cacophonious", "cacophonus", "cacaphonous"],
     "Contains '-phonous' — from Greek 'kakophonos.'", ["greek-origin"]),
    ("calligraphy", ["caligraphy", "calligrafy", "calligraphi"],
     "Double 'l' and 'ph' — from Greek 'kalligraphia.'", ["double-letter", "greek-origin"]),
    ("camaraderie", ["comraderie", "camaradery", "cameraderie"],
     "Contains '-aderie' — from French 'camaraderie.'", ["french-origin"]),
    ("catechism", ["catachism", "catechizm", "catichism"],
     "Contains '-echism' — from Greek 'katechismos.'", ["greek-origin"]),
    ("circumlocution", ["circumlocuton", "circunlocution", "circumlocusion"],
     "Contains 'circum-' + 'locution' — from Latin.", ["latin-origin"]),
    ("claustrophobia", ["claustraphobia", "claustrofobia", "clostrophobia"],
     "Contains '-phobia' — from Latin 'claustrum' + Greek 'phobos.'", ["latin-origin", "greek-origin"]),
    ("colloquialism", ["coloquialism", "colloqualizm", "colloquilism"],
     "Double 'l' and '-ialism' — from Latin 'colloquium.'", ["double-letter", "latin-origin"]),
    ("commiseration", ["comiseration", "commiseraton", "commiserasion"],
     "Double 'm' and '-tion' ending — commiserate + ion.", ["double-letter", "suffix"]),
    ("concatenation", ["concatination", "concatenaton", "concatanation"],
     "Contains '-ation' — concatenate → concatenation.", ["suffix"]),
    ("conflagration", ["conflagraton", "conflagrasion", "conflageration"],
     "Contains '-tion' — from Latin 'conflagrare.'", ["latin-origin"]),
    ("connoisseurship", ["connoiseurship", "conoisseurship", "connoissureship"],
     "Double 'n' and double 's' — connoisseur + ship.", ["french-origin", "double-letter"]),
    ("contretemps", ["contratamps", "contretempes", "contretamps"],
     "French word — silent final 's.'", ["french-origin", "silent-letter"]),
    ("coruscation", ["coruscaton", "corrusation", "coruscasion"],
     "One 'r' — from Latin 'coruscare.'", ["latin-origin"]),
    ("daguerreotype", ["daguerotype", "daguerrotype", "dagerreotype"],
     "Contains '-rreotype' — named after Daguerre.", ["french-origin", "double-letter"]),
    ("denouement", ["denoument", "denouemant", "denounement"],
     "French: dé + nouer + ment — silent final 't.'", ["french-origin", "silent-letter"]),
    ("desultory", ["desultary", "dessultory", "desultury"],
     "One 's' and '-ory' ending — from Latin 'desultorius.'", ["latin-origin"]),
    ("dilettante", ["diletante", "dilettanti", "dilletante"],
     "Double 't' — from Italian 'dilettante.'", ["double-letter"]),
    ("ebullient", ["ebuliant", "ebulient", "ebulliant"],
     "Double 'l' and '-ient' ending — from Latin 'ebullire.'", ["double-letter", "latin-origin"]),
    ("efflorescence", ["eflorescence", "efflorescense", "efflorescance"],
     "Double 'f' and '-escence' ending — from Latin 'efflorescere.'", ["double-letter", "latin-origin"]),
    ("egregious", ["egregeous", "egregous", "egrigious"],
     "Contains '-egious' — from Latin 'egregius.'", ["latin-origin"]),
    ("elocution", ["elocuton", "ellocution", "elocusion"],
     "One 'l' — from Latin 'elocutio.'", ["latin-origin"]),
    ("emollient", ["emoliant", "emolliant", "emolent"],
     "Double 'l' and '-ient' ending — from Latin 'emollire.'", ["double-letter", "latin-origin"]),
    ("ephemeral", ["ephemoral", "efemeral", "ephemiral"],
     "Contains 'ph' and '-eral' — from Greek 'ephemeros.'", ["greek-origin"]),
    ("equanimity", ["equanmity", "equanimety", "equanimmity"],
     "Contains '-animity' — from Latin 'aequanimitas.'", ["latin-origin"]),
    ("equivocation", ["equivocaton", "equivacation", "equivocasion"],
     "Contains '-tion' — equivocate → equivocation.", ["latin-origin", "suffix"]),
    ("extemporaneous", ["extemporanious", "extemporanous", "extemperaneous"],
     "Contains '-aneous' — from Latin 'extemporaneus.'", ["latin-origin"]),
    ("extraterrestrial", ["extraterestrial", "extraterrestreal", "extraterestreal"],
     "Double 'r' — extra + terrestrial.", ["double-letter", "latin-origin"]),
    ("flocculent", ["floculent", "floccullent", "flocculant"],
     "Double 'c' and '-ulent' ending — from Latin 'flocculentus.'", ["double-letter", "latin-origin"]),
    ("genuflection", ["genuflexion", "genuflecton", "genuflecsion"],
     "Contains '-tion' — genuflect → genuflection.", ["latin-origin", "suffix"]),
    ("grandiloquence", ["grandiloquance", "grandiloquense", "grandiloquince"],
     "Contains '-ence' — from Latin 'grandiloquentia.'", ["latin-origin", "suffix"]),
    ("halcyon", ["halcion", "halceon", "halcyion"],
     "Contains '-cyon' — from Greek 'halkyon.'", ["greek-origin"]),
    ("hegemony", ["hegemoney", "hegimony", "hegemeny"],
     "Contains '-emony' — from Greek 'hegemonia.'", ["greek-origin"]),
    ("hemorrhagic", ["hemoragic", "hemmorhagic", "hemorragic"],
     "Double 'r' and 'h' — hemorrhage + ic.", ["double-letter", "greek-origin"]),
    ("idiosyncrasy", ["idiosyncracy", "idiosyncricy", "idiosynchrasy"],
     "Ends in '-asy' not '-acy' — from Greek.", ["greek-origin"]),
    ("ignominious", ["ignominous", "ignomineous", "ignominnious"],
     "Contains '-inious' — from Latin 'ignominiosus.'", ["latin-origin"]),
    ("imperviousness", ["imperviousnes", "imperviouness", "imperviosness"],
     "Impervious + ness — retains '-ous.'", ["suffix"]),
    ("incommunicado", ["incomunicado", "incommunicaddo", "incommunicato"],
     "Double 'm' — from Spanish 'incomunicado.'", ["double-letter"]),
    ("incontrovertible", ["incontrovertable", "incontrovertibel", "incontravertible"],
     "Root 'controvert' is not standalone → '-ible.'", ["suffix"]),
    ("inefficacious", ["inefficatious", "inefficacous", "ineficacious"],
     "Double 'f' and '-acious' ending.", ["double-letter", "latin-origin"]),
    ("insouciance", ["insousiance", "insoucience", "insoucianse"],
     "Contains '-ance' — from French 'insouciance.'", ["french-origin", "suffix"]),
    ("irascibility", ["irascibilty", "irascability", "irasibility"],
     "Contains '-ibility' — irascible → irascibility.", ["suffix"]),
    ("legerdemain", ["legerdemaine", "legerdomain", "legerdemane"],
     "French: léger de main (light of hand).", ["french-origin"]),
    ("lugubrious", ["lugubrius", "lugubreous", "lugubriuos"],
     "Contains '-ious' — from Latin 'lugubris.'", ["latin-origin"]),
    ("machiavellian", ["machiavelian", "machiavellien", "machiavelien"],
     "Double 'l' — named after Machiavelli.", ["double-letter"]),
    ("magniloquence", ["magniloquance", "magniloquense", "magniloquince"],
     "Contains '-ence' — from Latin 'magniloquentia.'", ["latin-origin", "suffix"]),
    ("mellifluous", ["melifluous", "mellifluos", "mellifluious"],
     "Double 'l' — from Latin 'mellifluus.'", ["double-letter", "latin-origin"]),
    ("metamorphosis", ["metamorphisis", "metamorphoses", "metamorphasis"],
     "Contains '-phosis' — from Greek 'metamorphosis.'", ["greek-origin"]),
    ("milquetoast", ["milktoast", "milquetoste", "milqetoast"],
     "Contains '-que-' — named after Caspar Milquetoast.", ["unique-spelling"]),
    ("miscellany", ["miscelany", "miscelleny", "miscellaney"],
     "Double 'l' and '-any' ending — from Latin 'miscellanea.'", ["double-letter", "latin-origin"]),
    ("mischievousness", ["mischievousnes", "mischevousness", "mischieviosness"],
     "Mischievous + ness — no extra 'i.'", ["suffix"]),
    ("obsequiousness", ["obsequiousnes", "obsequiosness", "obsequiuosness"],
     "Obsequious + ness.", ["suffix"]),
    ("obstreperous", ["obstreprous", "obstreperious", "obstreporus"],
     "Contains '-erous' — from Latin 'obstreperus.'", ["latin-origin"]),
    ("onomatopoeic", ["onomatopeic", "onomatopoeik", "onomatapoiec"],
     "Contains '-poeic' — from 'onomatopoeia.'", ["greek-origin"]),
    ("ophthalmology", ["opthalmology", "ophthamology", "opthomology"],
     "Contains 'phth' — from Greek 'ophthalmos.'", ["greek-origin"]),
    ("parallelogram", ["paralelogram", "parallelagram", "parallellogram"],
     "Double 'l' in middle — parallel + ogram.", ["double-letter", "greek-origin"]),
    ("periphrastic", ["perifhrastic", "periphrastik", "periphrasic"],
     "Contains 'phr' — from Greek 'periphrastikos.'", ["greek-origin"]),
    ("perspicuity", ["perspicuety", "perspicuaty", "perspicuiti"],
     "Contains '-uity' — from Latin 'perspicuitas.'", ["latin-origin"]),
    ("phantasmagoria", ["fantasmagoria", "phantasmagora", "phantasmagoriea"],
     "Contains 'ph' — from French 'fantasmagorie.'", ["french-origin", "greek-origin"]),
    ("physiognomy", ["physiognamy", "physionomy", "physiogonomy"],
     "Contains '-gnomy' — from Greek 'physiognomonia.'", ["greek-origin"]),
    ("plethora", ["plethera", "plethorah", "plethorra"],
     "Contains '-ora' — from Greek 'plethore.'", ["greek-origin"]),
    ("pneumatic", ["neumatic", "pnuematic", "pneumatik"],
     "Silent 'p' — from Greek 'pneumatikos.'", ["greek-origin", "silent-letter"]),
    ("polysyllabic", ["polysylabic", "polysyllabik", "polysylabick"],
     "Double 'l' — poly + syllabic.", ["double-letter", "greek-origin"]),
    ("prestidigitator", ["prestidigitater", "prestidigiator", "prestidigittor"],
     "Contains '-digitator' — from French.", ["french-origin"]),
    ("protuberance", ["protuberence", "protuberanse", "protruberance"],
     "Contains '-ance' — from Latin 'protuberantia.'", ["latin-origin", "suffix"]),
    ("pusillanimity", ["pusilanimity", "pusillanimety", "pusillannimity"],
     "Double 'l' — from Latin 'pusillanimitas.'", ["double-letter", "latin-origin"]),
    ("querulous", ["querelous", "querulus", "querulious"],
     "Contains '-ulous' — from Latin 'querulus.'", ["latin-origin"]),
    ("quintessentially", ["quintesentially", "quinessentially", "quintessentialy"],
     "Double 's' — quintessential + ly.", ["double-letter"]),
    ("rapprochement", ["rapprochment", "raprochement", "rapprochament"],
     "Double 'p' — from French 'rapprochement.'", ["double-letter", "french-origin"]),
    ("recrudescent", ["recrudescant", "recrudecent", "recrudessent"],
     "Contains '-escent' — from Latin 'recrudescere.'", ["latin-origin"]),
    ("remonstrance", ["remonstrence", "remonstranse", "remonsterance"],
     "Contains '-ance' — remonstrate → remonstrance.", ["suffix"]),
    ("resplendent", ["resplendant", "resplendint", "resplendient"],
     "Ends in '-ent' — from Latin 'resplendens.'", ["latin-origin", "suffix"]),
    ("sacrosanct", ["sacrosankt", "sacrosanked", "sacrasanct"],
     "Contains '-sanct' — from Latin 'sacrosanctus.'", ["latin-origin"]),
    ("schizophrenia", ["schizophrena", "skizophrenia", "schizophrinia"],
     "Contains 'sch-' and 'phr' — from Greek 'schizein' + 'phren.'", ["greek-origin"]),
    ("sesquicentennial", ["sesquicentenial", "sesquicentennel", "sesquicentinnial"],
     "Contains '-ennial' — sesqui + centennial.", ["latin-origin"]),
    ("soliloquy", ["soliloquey", "soliliquy", "soliloqy"],
     "Contains '-loquy' — from Latin 'soliloquium.'", ["latin-origin"]),
    ("somnambulism", ["somnambulizm", "somnamblism", "somnambulsim"],
     "Contains '-ambulism' — from Latin 'somnus' + 'ambulare.'", ["latin-origin"]),
    ("staphylococcus", ["staphylococous", "staphylococus", "staphyloccocus"],
     "Double 'c' — from Greek 'staphyle' + 'kokkos.'", ["double-letter", "greek-origin"]),
    ("streptococcus", ["streptococous", "streptococus", "streptoccocus"],
     "Double 'c' — from Greek 'streptos' + 'kokkos.'", ["double-letter", "greek-origin"]),
    ("supererogatory", ["supererogitory", "supererogetary", "superrogatory"],
     "Contains '-atory' — from Latin 'supererogare.'", ["latin-origin", "suffix"]),
    ("sycophantic", ["sycophantik", "sycofantic", "sychophantic"],
     "Contains 'ph' — from Greek 'sykophantes.'", ["greek-origin"]),
    ("tautological", ["tautologicle", "tautologikal", "tautologicall"],
     "Contains '-logical' — from Greek 'tautologia.'", ["greek-origin"]),
    ("terpsichorean", ["terpischorean", "terpsichorein", "terpsichorian"],
     "From Terpsichore (Greek muse of dance).", ["greek-origin"]),
    ("thoroughfare", ["thorofare", "thoroughfair", "thoroghfare"],
     "Contains 'thorough' + 'fare.'", ["compound-word"]),
    ("tranquillity", ["tranquility", "tranquillety", "tranquilety"],
     "Double 'l' — from Latin 'tranquillitas.'", ["double-letter", "latin-origin"]),
    ("transliteration", ["transliteraton", "translitaration", "transliterasion"],
     "Contains '-tion' — transliterate → transliteration.", ["suffix"]),
    ("unconscionability", ["unconscionabilty", "unconcionability", "unconscionabilety"],
     "Contains '-ability' — unconscionable → unconscionability.", ["suffix"]),
    ("unimpeachability", ["unimpeachabilty", "unimpeachabilety", "unimpeachibility"],
     "Contains '-ability' — unimpeachable → unimpeachability.", ["suffix"]),
    ("verisimilitudinous", ["verisimilitudinious", "verisimiltudinos", "verisimilitudonous"],
     "From 'verisimilitude' + '-inous.'", ["latin-origin"]),
    ("vicissitudinous", ["vicissitudinious", "vicisitudinous", "vicissitudonous"],
     "From 'vicissitude' + '-inous.'", ["latin-origin", "double-letter"]),
    ("vouchsafe", ["vouchsave", "vouchsaf", "vouch-safe"],
     "Compound: vouch + safe — one word, no hyphen.", ["compound-word"]),
    ("zeitgeist", ["zietgeist", "zeitgiest", "zeitgist"],
     "German compound: Zeit (time) + Geist (spirit).", ["unique-spelling"]),
    ("acquiescence", ["aquiescence", "acquiesense", "acquiecense"],
     "Contains 'cqu' and '-escence' — from Latin 'acquiescere.'", ["latin-origin"]),
]
