# fmt: off
EXTRA_EASY = [
("The prefix 'dis-' in 'dislike' means:",["again","before","not/opposite","under"],"not/opposite","'Dis-' means 'not' or 'opposite.' Dislike = the opposite of like.",["word formation","prefixes"]),
("Which suffix makes 'enjoy' into a noun?",["'-ful'","'-ment'","'-less'","'-ly'"],"'-ment'","'-ment' creates nouns from verbs. Enjoy → enjoyment.",["word formation","suffixes"]),
("What is the root word in 'reusable'?",["re","use","able","reuse"],"use","The root is 'use.' 're-' means again, '-able' means capable of.",["word formation","root words"]),
("The prefix 'over-' in 'overflow' means:",["under","not","too much/beyond","again"],"too much/beyond","'Over-' means 'too much' or 'beyond.' Overflow = to flow beyond capacity.",["word formation","prefixes"]),
("The suffix '-ful' in 'beautiful' means:",["without","one who","full of","the act of"],"full of","'-ful' means 'full of.' Beautiful = full of beauty.",["word formation","suffixes"]),
("What does 'mis-' mean in 'mistake'?",["not","again","wrongly","before"],"wrongly","'Mis-' means 'wrongly.' Mistake = something taken/understood wrongly.",["word formation","prefixes"]),
("The suffix '-able' in 'washable' means:",["without","one who","capable of being","the act of"],"capable of being","'-able' means 'capable of being.' Washable = capable of being washed.",["word formation","suffixes"]),
("The root 'form' in 'transform' means:",["carry","shape","write","break"],"shape","'Form' means 'shape.' Transform = to change shape across.",["word formation","root words"]),
("What does the prefix 'un-' mean in 'untie'?",["not","reverse","again","before"],"reverse","In 'untie,' 'un-' means 'reverse the action.' Untie = reverse the tying.",["word formation","prefixes"]),
("The suffix '-ment' in 'movement' indicates:",["one who moves","the act of moving","without moving","full of movement"],"the act of moving","'-ment' creates nouns meaning 'act or result of.' Movement = the act of moving.",["word formation","suffixes"]),
("Which word has a suffix meaning 'without'?",["hopeful","homeless","teacher","kindness"],"homeless","'-less' means 'without.' Homeless = without a home.",["word formation","suffixes"]),
("The prefix 'super-' in 'superman' means:",["under","not","above/beyond","again"],"above/beyond","'Super-' means 'above' or 'beyond.' Superman = a man beyond normal abilities.",["word formation","prefixes"]),
("What is the root word in 'unhappiness'?",["un","happy","ness","unhappy"],"happy","The root is 'happy.' 'Un-' means not, '-ness' creates a noun.",["word formation","root words"]),
("The suffix '-er' in 'faster' indicates:",["one who","comparative degree","full of","the act of"],"comparative degree","When '-er' is added to adjectives, it shows comparison. Faster = more fast.",["word formation","suffixes","inflection"]),
("Which prefix means 'between' in 'interact'?",["in-","inter-","intra-","intro-"],"inter-","'Inter-' means 'between.' Interact = to act between/with each other.",["word formation","prefixes"]),
("The suffix '-tion' changes 'collect' into:",["an adjective","a noun","an adverb","another verb"],"a noun","'-tion' creates nouns from verbs. Collect → collection.",["word formation","suffixes","word class"]),
("What does 'dis-' mean in 'disappear'?",["again","before","away/not","under"],"away/not","'Dis-' means 'away' or 'not.' Disappear = to go away from sight.",["word formation","prefixes"]),
("The root 'move' in 'removal' means:",["to stay","to change position","to write","to see"],"to change position","'Move' means 'to change position.' Removal = the act of moving away.",["word formation","root words"]),
("Which suffix creates a noun from 'free'?",["'-ly'","'-dom'","'-ful'","'-ize'"],"'-dom'","'-dom' creates nouns meaning 'state of.' Free → freedom = the state of being free.",["word formation","suffixes"]),
("The prefix 'anti-' in 'antibiotic' means:",["for","before","against","with"],"against","'Anti-' means 'against.' Antibiotic = against life (bacteria).",["word formation","prefixes"]),
("What is the root word in 'unfriendly'?",["un","friend","ly","unfriend"],"friend","The root is 'friend.' 'Un-' means not, '-ly' makes it an adverb/adjective.",["word formation","root words"]),
("The suffix '-ize' in 'organize' means:",["full of","without","to make","one who"],"to make","'-ize' means 'to make.' Organize = to make into an ordered arrangement.",["word formation","suffixes"]),
("Which word contains a prefix meaning 'after'?",["preview","postwar","subway","redo"],"postwar","'Post-' means 'after.' Postwar = after the war.",["word formation","prefixes"]),
("The suffix '-ous' in 'famous' means:",["without","full of/having","one who","to make"],"full of/having","'-ous' means 'full of' or 'having.' Famous = having fame.",["word formation","suffixes"]),
("What does 'co-' mean in 'coworker'?",["against","not","together/with","before"],"together/with","'Co-' means 'together' or 'with.' Coworker = one who works together with you.",["word formation","prefixes"]),
("The root 'light' in 'enlighten' means:",["dark","heavy","illumination","quick"],"illumination","'Light' means 'illumination.' Enlighten = to bring light/understanding to.",["word formation","root words"]),
("Which suffix changes 'soft' into an adverb?",["'-ness'","'-ful'","'-ly'","'-en'"],"'-ly'","'-ly' creates adverbs from adjectives. Soft → softly = in a soft manner.",["word formation","suffixes"]),
("The prefix 'non-' in 'nonsense' means:",["again","before","not","under"],"not","'Non-' means 'not.' Nonsense = not sense = something without meaning.",["word formation","prefixes"]),
("What is the root word in 'replacement'?",["re","place","ment","replace"],"place","The root is 'place.' 're-' means again/back, '-ment' creates a noun.",["word formation","root words"]),
("The suffix '-ist' in 'pianist' means:",["the study of","full of","one who plays/practices","without"],"one who plays/practices","'-ist' means 'one who practices.' Pianist = one who plays piano.",["word formation","suffixes"]),
("Which prefix means 'too much' in 'overeat'?",["over-","out-","up-","on-"],"over-","'Over-' means 'too much.' Overeat = to eat too much.",["word formation","prefixes"]),
("The suffix '-ness' in 'weakness' means:",["one who","the state of","to make","full of"],"the state of","'-ness' means 'the state or quality of.' Weakness = the state of being weak.",["word formation","suffixes"]),
("What does 'de-' mean in 'defrost'?",["again","before","remove/reverse","under"],"remove/reverse","'De-' means 'remove' or 'reverse.' Defrost = to remove frost.",["word formation","prefixes"]),
("The root 'work' in 'worker' means:",["to play","to labor","to rest","to write"],"to labor","'Work' means 'to labor.' Worker = one who labors.",["word formation","root words"]),
("Which suffix makes 'child' into an adjective?",["'-ish'","'-ment'","'-tion'","'-er'"],"'-ish'","'-ish' creates adjectives. Child → childish = resembling a child.",["word formation","suffixes"]),
("The prefix 'out-' in 'outrun' means:",["not","under","surpass","again"],"surpass","'Out-' means 'to surpass.' Outrun = to run faster/farther than.",["word formation","prefixes"]),
("What is the root word in 'disagreeable'?",["dis","agree","able","disagree"],"agree","The root is 'agree.' 'Dis-' means not, '-able' means capable of.",["word formation","root words"]),
("The suffix '-ful' in 'thankful' creates a:",["noun","verb","adjective","adverb"],"adjective","'-ful' creates adjectives meaning 'full of.' Thankful = full of thanks.",["word formation","suffixes","word class"]),
("Which word has a prefix meaning 'self'?",["bicycle","automobile","telephone","submarine"],"automobile","'Auto-' means 'self.' Automobile = self-moving vehicle.",["word formation","prefixes"]),
("The suffix '-ment' in 'agreement' means:",["one who agrees","the result of agreeing","without agreeing","to agree again"],"the result of agreeing","'-ment' creates nouns meaning 'result of.' Agreement = the result of agreeing.",["word formation","suffixes"]),
("What does 'un-' mean in 'uncover'?",["not","reverse","again","before"],"reverse","In 'uncover,' 'un-' means 'reverse.' Uncover = to reverse the covering = to reveal.",["word formation","prefixes"]),
("The root 'build' in 'rebuild' means:",["to destroy","to construct","to paint","to clean"],"to construct","'Build' means 'to construct.' Rebuild = to construct again.",["word formation","root words"]),
("Which suffix changes 'dark' into a verb?",["'-ness'","'-ly'","'-en'","'-ful'"],"'-en'","'-en' creates verbs meaning 'to make.' Dark → darken = to make dark.",["word formation","suffixes"]),
("The prefix 'mis-' in 'mislead' means:",["not","again","wrongly","before"],"wrongly","'Mis-' means 'wrongly.' Mislead = to lead wrongly = to deceive.",["word formation","prefixes"]),
("What is the root word in 'unthinkable'?",["un","think","able","unthink"],"think","The root is 'think.' 'Un-' means not, '-able' means capable of.",["word formation","root words"]),
("The suffix '-dom' in 'kingdom' means:",["one who","the state or realm of","without","to make"],"the state or realm of","'-dom' means 'state, realm, or condition.' Kingdom = the realm of a king.",["word formation","suffixes"]),
("Which prefix means 'half' in 'semicircle'?",["semi-","bi-","tri-","mono-"],"semi-","'Semi-' means 'half.' Semicircle = half a circle.",["word formation","prefixes"]),
("The suffix '-ive' in 'active' means:",["without","one who","tending to","the act of"],"tending to","'-ive' means 'tending to' or 'having the quality of.' Active = tending to act.",["word formation","suffixes"]),
("What does 'trans-' mean in 'transfer'?",["under","not","across","again"],"across","'Trans-' means 'across.' Transfer = to carry across.",["word formation","prefixes"]),
("The root 'count' in 'recount' means:",["to add up/tell","to subtract","to multiply","to divide"],"to add up/tell","'Count' means 'to add up' or 'to tell.' Recount = to count again or tell again.",["word formation","root words"]),
("Which suffix creates a noun from 'weak'?",["'-ly'","'-ness'","'-ful'","'-ize'"],"'-ness'","'-ness' creates nouns from adjectives. Weak → weakness.",["word formation","suffixes"]),
("The prefix 'fore-' in 'forecast' means:",["after","not","before/ahead","under"],"before/ahead","'Fore-' means 'before' or 'ahead.' Forecast = to cast/predict ahead of time.",["word formation","prefixes"]),
("What is the root word in 'misspelling'?",["mis","spell","ing","misspell"],"spell","The root is 'spell.' 'Mis-' means wrongly, '-ing' is a suffix.",["word formation","root words"]),
("The suffix '-ship' in 'friendship' means:",["one who","the state or quality of","without","to make"],"the state or quality of","'-ship' means 'state, quality, or skill.' Friendship = the state of being friends.",["word formation","suffixes"]),
("Which word contains a prefix meaning 'many'?",["bicycle","unicycle","multicolor","semicircle"],"multicolor","'Multi-' means 'many.' Multicolor = having many colors.",["word formation","prefixes"]),
("The suffix '-ful' in 'powerful' means:",["without","one who","full of","the act of"],"full of","'-ful' means 'full of.' Powerful = full of power.",["word formation","suffixes"]),
("What does 'sub-' mean in 'subtitle'?",["above","not","under/below","again"],"under/below","'Sub-' means 'under' or 'below.' Subtitle = a title below (the main title).",["word formation","prefixes"]),
("The root 'help' in 'helpful' means:",["to harm","to assist","to ignore","to stop"],"to assist","'Help' means 'to assist.' Helpful = full of assistance.",["word formation","root words"]),
("Which suffix changes 'hope' into an adjective meaning 'without hope'?",["'-ful'","'-less'","'-ment'","'-tion'"],"'-less'","'-less' means 'without.' Hope → hopeless = without hope.",["word formation","suffixes"]),
("The prefix 'bi-' in 'bilingual' means:",["one","two","three","many"],"two","'Bi-' means 'two.' Bilingual = speaking two languages.",["word formation","prefixes"]),
("What is the root word in 'unforgivable'?",["un","forgive","able","unforgive"],"forgive","The root is 'forgive.' 'Un-' means not, '-able' means capable of.",["word formation","root words"]),
("The suffix '-tion' in 'celebration' means:",["one who","the act of","without","full of"],"the act of","'-tion' means 'the act of.' Celebration = the act of celebrating.",["word formation","suffixes"]),
("Which prefix means 'against' in 'antiwar'?",["anti-","ante-","auto-","ambi-"],"anti-","'Anti-' means 'against.' Antiwar = against war.",["word formation","prefixes"]),
("The suffix '-er' in 'singer' means:",["comparative","one who does","full of","the act of"],"one who does","'-er' as an agent suffix means 'one who.' Singer = one who sings.",["word formation","suffixes"]),
("What does 'inter-' mean in 'interview'?",["within","under","between","against"],"between","'Inter-' means 'between.' Interview = a view/exchange between people.",["word formation","prefixes"]),
("The root 'play' in 'replay' means:",["to work","to engage in activity for fun","to rest","to study"],"to engage in activity for fun","'Play' means 'to engage in activity.' Replay = to play again.",["word formation","root words"]),
("Which suffix makes 'comfort' into an adjective?",["'-ment'","'-able'","'-tion'","'-er'"],"'-able'","'-able' creates adjectives. Comfort → comfortable = capable of giving comfort.",["word formation","suffixes"]),
("The prefix 'ex-' in 'exit' means:",["into","under","out","again"],"out","'Ex-' means 'out.' Exit = a way out.",["word formation","prefixes"]),
("What is the root word in 'unbelievable'?",["un","believe","able","unbelieve"],"believe","The root is 'believe.' 'Un-' means not, '-able' means capable of.",["word formation","root words"]),
("The suffix '-ment' in 'excitement' creates a:",["verb","noun","adjective","adverb"],"noun","'-ment' creates nouns. Excitement = the state of being excited.",["word formation","suffixes","word class"]),
("Which prefix means 'one' in 'unicorn'?",["uni-","bi-","tri-","mono-"],"uni-","'Uni-' means 'one.' Unicorn = one horn.",["word formation","prefixes"]),
("The root 'kind' in 'unkind' means:",["cruel","gentle/caring","strong","fast"],"gentle/caring","'Kind' means 'gentle' or 'caring.' Unkind = not kind.",["word formation","root words"]),
("What does the suffix '-ish' do to 'child'?",["makes it a noun","makes it an adjective","makes it a verb","makes it an adverb"],"makes it an adjective","'-ish' creates adjectives meaning 'resembling.' Childish = resembling a child.",["word formation","suffixes","word class"]),
("The prefix 'down-' in 'download' means:",["up","not","from above to below","again"],"from above to below","'Down-' indicates direction from above to below. Download = to load from a remote source down to your device.",["word formation","prefixes"]),
("Which word has a root meaning 'to hear'?",["inspect","audience","describe","transport"],"audience","'Aud' means 'to hear.' Audience = those who hear/listen.",["word formation","root words"]),
("The suffix '-ment' in 'payment' means:",["one who pays","the act/result of paying","without paying","to pay again"],"the act/result of paying","'-ment' creates nouns. Payment = the act or result of paying.",["word formation","suffixes"]),
]
# fmt: on

# fmt: off
EXTRA_EASY += [
("The suffix '-ment' in 'treatment' creates a:",["verb","noun","adjective","adverb"],"noun","'-ment' creates nouns from verbs. Treatment = the act of treating.",["word formation","suffixes","word class"]),
("What does 'un-' mean in 'unlock'?",["not","reverse","again","before"],"reverse","In 'unlock,' 'un-' means 'reverse the action.' Unlock = reverse the locking.",["word formation","prefixes"]),
("Which word has a prefix meaning 'before'?",["redo","unhappy","prewash","subway"],"prewash","'Pre-' means 'before.' Prewash = wash before (the main wash).",["word formation","prefixes"]),
("The root 'write' in 'rewrite' means:",["to read","to put words on paper","to erase","to speak"],"to put words on paper","'Write' means 'to put words on paper.' Rewrite = to write again.",["word formation","root words"]),
]
# fmt: on
