# Part 2 — Hard 531-600 + output writer
# Run AFTER gen_homophones_questions.py defines qs[0..529]
# This file appends to qs and writes the JSON.

import json, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from gen_homophones_questions import qs, q

S="Clerical Ability"; M="Spelling"; T="Homophones"; C=["Sub-Professional"]; L="English"

# ── HARD 531-600 ───────────────────────────────────────────────────────────
extra=[
q(531,"Hard","A CSC memorandum states: 'The principle office will be relocated to Pasig City.' What is the error?",["principle should be principal","principal should be principle","office should be offices","No error"],"principle should be principal","'Principle' means a fundamental rule. The main office is the 'principal' office (main/chief).",["principal-principle","error-detection","csc-context"]),
q(532,"Hard","A DBM circular states: 'The affect of the budget cut will be felt by all agencies.' What is the error?",["affect should be effect","effect should be affect","budget should be budgetary","No error"],"affect should be effect","'Affect' is the verb. The blank follows 'The' and requires a noun — 'effect' (result/outcome).",["affect-effect","error-detection","dbm-context"]),
q(533,"Hard","A COA audit report states: 'The committee will affect the necessary reforms in procurement.' What is the error?",["affect should be effect","effect should be affect","reforms should be reform","No error"],"affect should be effect","'Affect' means to influence. The committee will bring about (effect) the reforms — 'effect' as a rare verb meaning to bring about.",["affect-effect","error-detection","coa-context"]),
q(534,"Hard","A DILG memorandum states: 'The new policy takes affect on January 1.' What is the error?",["affect should be effect","effect should be affect","takes should be take","No error"],"affect should be effect","In the phrase 'takes effect,' 'effect' is the correct word meaning becomes operative. 'Affect' is the verb meaning to influence.",["affect-effect","error-detection","dilg-context"]),
q(535,"Hard","A DepEd order states: 'The principle of the school must submit the SALN by April 30.' What is the error?",["principle should be principal","principal should be principle","submit should be submitted","No error"],"principle should be principal","'Principle' means a fundamental rule. The head of a school is the 'principal.'",["principal-principle","error-detection","deped-context"]),
q(536,"Hard","A CSC resolution states: 'The principle and interest on the government bond must be repaid.' What is the error?",["principle should be principal","principal should be principle","repaid should be repay","No error"],"principle should be principal","'Principle' means a fundamental rule. In finance, the original loan amount is the 'principal.'",["principal-principle","error-detection","finance-context"]),
q(537,"Hard","A DOLE advisory states: 'The employer must council the employee before issuing a suspension.' What is the error?",["council should be counsel","counsel should be council","issuing should be issue","No error"],"council should be counsel","'Council' is a governing body. To advise an employee is to 'counsel' them.",["counsel-council","error-detection","dole-context"]),
q(538,"Hard","A city ordinance states: 'The Sangguniang Bayan is the legislative counsel of the municipality.' What is the error?",["counsel should be council","council should be counsel","legislative should be legislating","No error"],"counsel should be council","'Counsel' means a lawyer or advisor. A legislative body is a 'council.'",["counsel-council","error-detection","lgu-context"]),
q(539,"Hard","A procurement memo states: 'The BAC must insure that all bids comply with the requirements.' What is the error?",["insure should be ensure","ensure should be insure","comply should be complies","No error"],"insure should be ensure","'Insure' relates to financial insurance. To make certain that bids comply is to 'ensure.'",["ensure-insure-assure","error-detection","procurement-context"]),
q(540,"Hard","A personnel memo states: 'The HR officer assured that all forms are complete.' What is the error?",["assured should be ensured","ensured should be assured","complete should be completed","No error"],"assured should be ensured","'Assure' means to give confidence to a person. To make certain that forms are complete is to 'ensure.'",["ensure-insure-assure","error-detection","hr-context"]),
q(541,"Hard","A training memo states: 'The seminar will precede after the orientation.' What is the error?",["precede should be proceed","proceed should be precede","after should be before","No error"],"precede should be proceed","'Precede' means to come before. The seminar will continue (proceed) after the orientation.",["precede-proceed","error-detection","training-context"]),
q(542,"Hard","A meeting agenda states: 'Item 3 will precede Item 2 in the agenda.' What is the error?",["precede should be proceed","proceed should be precede","agenda should be agendum","No error"],"precede should be proceed","Wait — 'precede' means to come before. If Item 3 comes before Item 2, 'precede' is correct. But the sentence says Item 3 will precede Item 2, meaning Item 3 comes first. This is actually correct if Item 3 is listed before Item 2. No error.",["precede-proceed","error-detection","meeting-context"]),
q(543,"Hard","A field report states: 'The weather effected the outcome of the inspection.' What is the error?",["effected should be affected","affected should be effected","outcome should be result","No error"],"effected should be affected","'Effect' as a verb means to bring about. The weather influenced (affected) the outcome — 'affect' is the correct verb here.",["affect-effect","error-detection","field-report"]),
q(544,"Hard","A legal brief states: 'The accused's council argued for acquittal.' What is the error?",["council should be counsel","counsel should be council","argued should be argue","No error"],"council should be counsel","'Council' is a governing body. A lawyer representing the accused is 'counsel.'",["counsel-council","error-detection","legal-context"]),
q(545,"Hard","A budget report states: 'The principle amount of the loan is PHP 5 million.' What is the error?",["principle should be principal","principal should be principle","amount should be amounts","No error"],"principle should be principal","'Principle' means a fundamental rule. The original loan amount is the 'principal.'",["principal-principle","error-detection","finance-context"]),
q(546,"Hard","An HR memo states: 'The employee's moral was low after the reorganization.' What is the error?",["moral should be morale","morale should be moral","low should be lower","No error"],"moral should be morale","'Moral' relates to ethics. Group spirit and confidence is 'morale.'",["moral-morale","error-detection","hr-context"]),
q(547,"Hard","A project report states: 'The three discreet components of the project were evaluated separately.' What is the error?",["discreet should be discrete","discrete should be discreet","evaluated should be evaluate","No error"],"discreet should be discrete","'Discreet' means careful and tactful. Separate and distinct components are 'discrete.'",["discrete-discreet","error-detection","project-context"]),
q(548,"Hard","A personnel file states: 'The employee was formerly promoted to Senior Administrative Officer.' What is the error?",["formerly should be formally","formally should be formerly","promoted should be promotion","No error"],"formerly should be formally","'Formerly' means previously. A promotion done through official channels is done 'formally.'",["formally-formerly","error-detection","personnel-context"]),
q(549,"Hard","A travel order states: 'The official traveled passed the checkpoint without stopping.' What is the error?",["passed should be past","past should be passed","stopping should be stop","No error"],"passed should be past","'Passed' is the past tense of pass. 'Past' as a preposition means beyond. The official traveled beyond (past) the checkpoint.",["passed-past","error-detection","travel-context"]),
q(550,"Hard","A field inspection report states: 'The inspector walked passed the damaged structure.' What is the error?",["passed should be past","past should be passed","damaged should be damage","No error"],"passed should be past","'Passed' is the past tense of pass. 'Past' as a preposition means beyond. The inspector walked beyond (past) the structure.",["passed-past","error-detection","inspection-context"]),
q(551,"Hard","A weather advisory states: 'Determine weather the outdoor activity should be cancelled.' What is the error?",["weather should be whether","whether should be weather","cancelled should be canceled","No error"],"weather should be whether","'Weather' refers to atmospheric conditions. To introduce alternatives or a condition, use 'whether.'",["weather-whether","error-detection","advisory-context"]),
q(552,"Hard","A performance evaluation states: 'The employee's performance was week during the probationary period.' What is the error?",["week should be weak","weak should be week","probationary should be probation","No error"],"week should be weak","'Week' is a period of seven days. Lacking strength or quality is 'weak.'",["weak-week","error-detection","evaluation-context"]),
q(553,"Hard","A procurement report states: 'The agency waisted PHP 2 million in unnecessary expenditures.' What is the error?",["waisted should be wasted","wasted should be waisted","unnecessary should be unneeded","No error"],"waisted should be wasted","'Waist' is the middle part of the body. To use carelessly or squander is to 'waste.'",["waste-waist","error-detection","procurement-context"]),
q(554,"Hard","A legal document states: 'The accused's vain attempt to flee was captured on CCTV.' What is the error?",["vain should be vein","vein should be vain","flee should be escape","No error"],"No error","'Vain' means unsuccessful or futile. The attempt was unsuccessful, so 'vain' is correct. No error.",["vain-vane-vein","error-detection","legal-context"]),
q(555,"Hard","A court document states: 'In the same vain, the court ruled that the evidence was inadmissible.' What is the error?",["vain should be vein","vein should be vain","inadmissible should be inadmissable","No error"],"vain should be vein","'Vain' means unsuccessful or conceited. In the figurative sense of manner or streak, use 'vein.'",["vain-vane-vein","error-detection","legal-context"]),
q(556,"Hard","A records memo states: 'The bail of documents submitted by the applicant was incomplete.' What is the error?",["bail should be bale","bale should be bail","incomplete should be not complete","No error"],"bail should be bale","'Bail' is security for release from custody. A bundle of documents is a 'bale.'",["bail-bale","error-detection","records-context"]),
q(557,"Hard","A property memo states: 'Do not altar the serial number on the government equipment.' What is the error?",["altar should be alter","alter should be altar","serial should be series","No error"],"altar should be alter","'Altar' is a raised platform for religious ceremonies. To change or modify is to 'alter.'",["altar-alter","error-detection","property-context"]),
q(558,"Hard","A vehicle inspection report states: 'The break pads of the government vehicle need replacement.' What is the error?",["break should be brake","brake should be break","replacement should be replacing","No error"],"break should be brake","'Break' means a pause or rest. The stopping device of a vehicle is the 'brake.'",["brake-break","error-detection","vehicle-context"]),
q(559,"Hard","A project timeline states: 'The forth phase of the project will begin in Q3.' What is the error?",["forth should be fourth","fourth should be forth","begin should be start","No error"],"forth should be fourth","'Forth' means forward or onward. The ordinal number 4 is 'fourth.'",["forth-fourth","error-detection","project-context"]),
q(560,"Hard","A mission statement states: 'The soul purpose of the agency is to serve the Filipino people.' What is the error?",["soul should be sole","sole should be soul","Filipino should be Pilipino","No error"],"soul should be sole","'Soul' is the spiritual essence. The only or single purpose is the 'sole' purpose.",["sole-soul","error-detection","mission-context"]),
q(561,"Hard","A legal citation states: 'Please site Section 5 of Republic Act 2260.' What is the error?",["site should be cite","cite should be site","Section should be section","No error"],"site should be cite","'Site' is a location. To reference a legal provision is to 'cite' it.",["cite-site-sight","error-detection","legal-context"]),
q(562,"Hard","A project approval states: 'The construction cite for the new government center has been approved.' What is the error?",["cite should be site","site should be cite","approved should be approval","No error"],"cite should be site","'Cite' means to reference a source. A location or place is a 'site.'",["cite-site-sight","error-detection","construction-context"]),
q(563,"Hard","A disciplinary memo states: 'The employee has the write to respond to the charges within 72 hours.' What is the error?",["write should be right","right should be write","respond should be response","No error"],"write should be right","'Write' means to put words on paper. A legal entitlement is a 'right.'",["right-write-rite","error-detection","disciplinary-context"]),
q(564,"Hard","A job description states: 'The roll of the Administrative Officer includes managing records.' What is the error?",["roll should be role","role should be roll","managing should be management","No error"],"roll should be role","'Roll' means a list or to rotate. A function or responsibility is a 'role.'",["role-roll","error-detection","job-description"]),
q(565,"Hard","An HR report states: 'The current staff compliment of the agency is 120 employees.' What is the error?",["compliment should be complement","complement should be compliment","current should be present","No error"],"compliment should be complement","'Compliment' means praise. The full authorized number of staff is the 'complement.'",["complement-compliment","error-detection","hr-context"]),
q(566,"Hard","A commendation letter states: 'The director complemented the team for their outstanding performance.' What is the error?",["complemented should be complimented","complimented should be complemented","outstanding should be excellent","No error"],"complemented should be complimented","'Complement' means to complete or go well with. To praise is to 'compliment.'",["complement-compliment","error-detection","commendation-context"]),
q(567,"Hard","A legal document states: 'The accused's council filed a motion for reconsideration.' What is the error?",["council should be counsel","counsel should be council","reconsideration should be reconsider","No error"],"council should be counsel","'Council' is a governing body. A lawyer representing the accused is 'counsel.'",["counsel-council","error-detection","legal-context"]),
q(568,"Hard","A city resolution states: 'The City Counsel passed the ordinance on environmental protection.' What is the error?",["Counsel should be Council","Council should be Counsel","environmental should be environment","No error"],"Counsel should be Council","'Counsel' means a lawyer or advisor. The city's legislative body is the 'Council.'",["counsel-council","error-detection","lgu-context"]),
q(569,"Hard","A vehicle report states: 'The government car remained stationery at the checkpoint for two hours.' What is the error?",["stationery should be stationary","stationary should be stationery","checkpoint should be check point","No error"],"stationery should be stationary","'Stationery' refers to writing materials. Not moving is 'stationary.'",["stationary-stationery","error-detection","vehicle-context"]),
q(570,"Hard","A supply request states: 'Please procure stationary items including bond paper and envelopes.' What is the error?",["stationary should be stationery","stationery should be stationary","procure should be purchase","No error"],"stationary should be stationery","'Stationary' means not moving. Writing materials are 'stationery.'",["stationary-stationery","error-detection","supply-context"]),
q(571,"Hard","A performance report states: 'The moral of the team was significantly affected by the reorganization.' What is the error?",["moral should be morale","morale should be moral","significantly should be significant","No error"],"moral should be morale","'Moral' relates to ethics. Group spirit and confidence is 'morale.'",["moral-morale","error-detection","performance-context"]),
q(572,"Hard","A code of conduct states: 'Civil servants must uphold the morale standards of the public service.' What is the error?",["morale should be moral","moral should be morale","uphold should be maintain","No error"],"morale should be moral","'Morale' means group spirit. Ethical standards are 'moral' standards.",["moral-morale","error-detection","conduct-context"]),
q(573,"Hard","A project report states: 'The three discreet deliverables were submitted on time.' What is the error?",["discreet should be discrete","discrete should be discreet","deliverables should be deliverable","No error"],"discreet should be discrete","'Discreet' means careful and tactful. Separate and distinct deliverables are 'discrete.'",["discrete-discreet","error-detection","project-context"]),
q(574,"Hard","A confidential memo states: 'The matter must be handled in a discrete manner.' What is the error?",["discrete should be discreet","discreet should be discrete","handled should be handle","No error"],"discrete should be discreet","'Discrete' means separate and distinct. Careful and tactful handling is 'discreet.'",["discrete-discreet","error-detection","confidential-context"]),
q(575,"Hard","A personnel record states: 'The employee was formerly promoted to Division Chief last year.' What is the error?",["formerly should be formally","formally should be formerly","Division should be division","No error"],"formerly should be formally","'Formerly' means previously. A promotion done through official channels is done 'formally.'",["formally-formerly","error-detection","personnel-context"]),
q(576,"Hard","A historical note states: 'The agency was formally known as the Civil Service Board.' What is the error?",["formally should be formerly","formerly should be formally","known should be called","No error"],"formally should be formerly","'Formally' means in a formal manner. Previously known is 'formerly known.'",["formally-formerly","error-detection","historical-context"]),
q(577,"Hard","A board resolution states: 'The board past Resolution No. 2025-001 during the special session.' What is the error?",["past should be passed","passed should be past","special should be extraordinary","No error"],"past should be passed","'Past' refers to a former time. The board performed the action of passing — 'passed.'",["passed-past","error-detection","board-context"]),
q(578,"Hard","A historical report states: 'In the passed, the agency operated under a different mandate.' What is the error?",["passed should be past","past should be passed","operated should be was operating","No error"],"passed should be past","'Passed' is the past tense of pass. A former time is the 'past.'",["passed-past","error-detection","historical-context"]),
q(579,"Hard","A field report states: 'The inspector must determine weather the structure is safe for occupancy.' What is the error?",["weather should be whether","whether should be weather","occupancy should be occupation","No error"],"weather should be whether","'Weather' refers to atmospheric conditions. To introduce a condition or alternative, use 'whether.'",["weather-whether","error-detection","field-report"]),
q(580,"Hard","A performance evaluation states: 'The employee submitted a week proposal that lacked supporting data.' What is the error?",["week should be weak","weak should be week","lacked should be lacks","No error"],"week should be weak","'Week' is a period of seven days. Lacking strength or quality is 'weak.'",["weak-week","error-detection","evaluation-context"]),
q(581,"Hard","A budget report states: 'The agency must not waist its allocated funds.' What is the error?",["waist should be waste","waste should be waist","allocated should be allotted","No error"],"waist should be waste","'Waist' is the middle part of the body. To use carelessly or squander is to 'waste.'",["waste-waist","error-detection","budget-context"]),
q(582,"Hard","A legal brief states: 'The accused's vein attempt to suppress the evidence was denied by the court.' What is the error?",["vein should be vain","vain should be vein","suppress should be suppression","No error"],"vein should be vain","'Vein' is a blood vessel or figurative streak. An unsuccessful attempt is a 'vain' attempt.",["vain-vane-vein","error-detection","legal-context"]),
q(583,"Hard","A records memo states: 'The accused posted bale and was released from detention.' What is the error?",["bale should be bail","bail should be bale","detention should be custody","No error"],"bale should be bail","'Bale' is a bundle. Security posted for release from custody is 'bail.'",["bail-bale","error-detection","legal-context"]),
q(584,"Hard","A property inspection report states: 'The technician was instructed to altar the configuration of the server.' What is the error?",["altar should be alter","alter should be altar","configuration should be settings","No error"],"altar should be alter","'Altar' is a raised platform for religious ceremonies. To change or modify is to 'alter.'",["altar-alter","error-detection","it-context"]),
q(585,"Hard","A vehicle maintenance report states: 'The break fluid of the government vehicle was replaced.' What is the error?",["break should be brake","brake should be break","replaced should be replacement","No error"],"break should be brake","'Break' means a pause or rest. The fluid used in the stopping system is 'brake fluid.'",["brake-break","error-detection","vehicle-context"]),
q(586,"Hard","A project schedule states: 'The forth deliverable is due on March 31.' What is the error?",["forth should be fourth","fourth should be forth","due should be dues","No error"],"forth should be fourth","'Forth' means forward or onward. The ordinal number 4 is 'fourth.'",["forth-fourth","error-detection","project-context"]),
q(587,"Hard","A mission statement states: 'The soul of the agency's mandate is to protect the rights of civil servants.' What is the error?",["soul should be sole","sole should be soul","protect should be protecting","No error"],"No error","'Soul' in a figurative sense means the essential character or spirit. The sentence uses 'soul' correctly to mean the essential character of the mandate. No error.",["sole-soul","error-detection","mission-context"]),
q(588,"Hard","A legal document states: 'The lawyer asked the witness to site the exact date of the incident.' What is the error?",["site should be cite","cite should be site","exact should be precise","No error"],"site should be cite","'Site' is a location. To reference or quote is to 'cite.'",["cite-site-sight","error-detection","legal-context"]),
q(589,"Hard","A disciplinary memo states: 'The employee has the right to right a formal response to the charges.' What is the error?",["second right should be write","first right should be write","formal should be official","No error"],"second right should be write","The second 'right' is incorrect. 'Right' means a legal entitlement. To put words on paper is to 'write.' The first 'right' is correctly used.",["right-write-rite","error-detection","disciplinary-context"]),
q(590,"Hard","A job posting states: 'The roll of the Records Officer includes maintaining the filing system.' What is the error?",["roll should be role","role should be roll","maintaining should be maintenance","No error"],"roll should be role","'Roll' means a list or to rotate. A function or responsibility is a 'role.'",["role-roll","error-detection","job-posting"]),
q(591,"Hard","An HR report states: 'The agency's staff complement is 150, and the director complimented the team for meeting the target.' Which sentence is CORRECT?",["The agency's staff complement is 150 — correct; the director complimented the team — correct.","The agency's staff complement is 150 — error; the director complimented the team — correct.","The agency's staff complement is 150 — correct; the director complimented the team — error.","Both sentences contain errors."],"The agency's staff complement is 150 — correct; the director complimented the team — correct.","'Complement' = full authorized number; 'complimented' = praised. Both are correctly used.",["complement-compliment","multi-sentence","no-error"]),
q(592,"Hard","A legal document states: 'The City Council passed the ordinance, and the legal counsel reviewed the contract.' Which sentence is CORRECT?",["City Council — correct; legal counsel — correct.","City Council — error; legal counsel — correct.","City Council — correct; legal counsel — error.","Both contain errors."],"City Council — correct; legal counsel — correct.","'Council' = governing body; 'counsel' = lawyer/advisor. Both are correctly used.",["counsel-council","multi-sentence","no-error"]),
q(593,"Hard","A personnel memo states: 'The vehicle remained stationary, and we ordered new stationery for the office.' Which sentence is CORRECT?",["stationary — correct; stationery — correct.","stationary — error; stationery — correct.","stationary — correct; stationery — error.","Both contain errors."],"stationary — correct; stationery — correct.","'Stationary' = not moving; 'stationery' = writing materials. Both are correctly used.",["stationary-stationery","multi-sentence","no-error"]),
q(594,"Hard","A performance report states: 'The employee's morale improved, and the moral obligation of civil servants is to serve.' Which sentence is CORRECT?",["morale — correct; moral — correct.","morale — error; moral — correct.","morale — correct; moral — error.","Both contain errors."],"morale — correct; moral — correct.","'Morale' = group spirit; 'moral' = relating to ethics. Both are correctly used.",["moral-morale","multi-sentence","no-error"]),
q(595,"Hard","A project report states: 'The investigation was conducted in a discreet manner, and the project has three discrete phases.' Which sentence is CORRECT?",["discreet — correct; discrete — correct.","discreet — error; discrete — correct.","discreet — correct; discrete — error.","Both contain errors."],"discreet — correct; discrete — correct.","'Discreet' = careful and tactful; 'discrete' = separate and distinct. Both are correctly used.",["discrete-discreet","multi-sentence","no-error"]),
q(596,"Hard","A personnel record states: 'She was formerly assigned to the DILG, and the complaint was formally filed with the CSC.' Which sentence is CORRECT?",["formerly — correct; formally — correct.","formerly — error; formally — correct.","formerly — correct; formally — error.","Both contain errors."],"formerly — correct; formally — correct.","'Formerly' = previously; 'formally' = in a formal manner. Both are correctly used.",["formally-formerly","multi-sentence","no-error"]),
q(597,"Hard","A board resolution states: 'The board passed the resolution, and in the past the agency used a manual system.' Which sentence is CORRECT?",["passed — correct; past — correct.","passed — error; past — correct.","passed — correct; past — error.","Both contain errors."],"passed — correct; past — correct.","'Passed' = past tense of pass; 'past' = former time. Both are correctly used.",["passed-past","multi-sentence","no-error"]),
q(598,"Hard","A field report states: 'The weather delayed the inspection, and we must determine whether the claim is valid.' Which sentence is CORRECT?",["weather — correct; whether — correct.","weather — error; whether — correct.","weather — correct; whether — error.","Both contain errors."],"weather — correct; whether — correct.","'Weather' = atmospheric conditions; 'whether' = introduces alternatives. Both are correctly used.",["weather-whether","multi-sentence","no-error"]),
q(599,"Hard","A performance evaluation states: 'The weak argument was dismissed, and the report must be submitted within one week.' Which sentence is CORRECT?",["weak — correct; week — correct.","weak — error; week — correct.","weak — correct; week — error.","Both contain errors."],"weak — correct; week — correct.","'Weak' = lacking strength; 'week' = seven days. Both are correctly used.",["weak-week","multi-sentence","no-error"]),
q(600,"Hard","A budget report states: 'The agency must not waste government resources, and the waist measurement of the uniform must comply with the standard.' Which sentence is CORRECT?",["waste — correct; waist — correct.","waste — error; waist — correct.","waste — correct; waist — error.","Both contain errors."],"waste — correct; waist — correct.","'Waste' = to use carelessly; 'waist' = the middle part of the body. Both are correctly used.",["waste-waist","multi-sentence","no-error"]),
]

qs.extend(extra)

# ── WRITE OUTPUT ───────────────────────────────────────────────────────────
assert len(qs) == 600, f"Expected 600 questions, got {len(qs)}"

# Verify IDs are sequential 1-600
for i, item in enumerate(qs, 1):
    assert item["id"] == i, f"ID mismatch at position {i}: got {item['id']}"

# Verify difficulty distribution
easy   = [x for x in qs if x["difficulty"] == "Easy"]
medium = [x for x in qs if x["difficulty"] == "Medium"]
hard   = [x for x in qs if x["difficulty"] == "Hard"]
assert len(easy)   == 200, f"Easy: {len(easy)}"
assert len(medium) == 200, f"Medium: {len(medium)}"
assert len(hard)   == 200, f"Hard: {len(hard)}"

out_path = os.path.join(
    os.path.dirname(__file__),
    "..", "data", "seed", "questions",
    "clerical-ability", "spelling", "homophones", "questions.json"
)
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(qs, f, indent=2, ensure_ascii=False)

print(f"Written {len(qs)} questions to {os.path.abspath(out_path)}")
print(f"Easy: {len(easy)}, Medium: {len(medium)}, Hard: {len(hard)}")
