"""
Rebuild Q201-Q400 (Medium) with diverse pairs, varied question types,
and unique sentence contexts. Covers all 16 previously-missing pairs.
Run: python scripts/rebuild_medium.py
"""
import json, os

PATH = "data/seed/questions/clerical-ability/spelling/homophones/questions.json"
S="Clerical Ability"; M="Spelling"; T="Homophones"; C=["Sub-Professional"]; L="English"

def q(i,d,question,choices,answer,explanation,tags):
    return {"id":i,"subtest":S,"module":M,"subtopic":T,"difficulty":d,
            "question":question,"choices":choices,"answer":answer,
            "explanation":explanation,"tags":tags,"category":C,"language":L}

medium = []

# ── BLOCK A: 16 MISSING PAIRS (Q201-Q232) ─────────────────────────────────
medium += [
# allowed / aloud
q(201,"Medium","Choose the word that correctly completes: 'Employees are _____ to take up to five days of sick leave per year.'",
  ["aloud","allowed","alowed","alowd"],"allowed",
  "'Allowed' means permitted. 'Aloud' means out loud or audibly. Employees are permitted to take leave.",
  ["allowed-aloud","verb"]),
q(202,"Medium","Choose the word that correctly completes: 'The resolution was read _____ during the plenary session.'",
  ["allowed","aloud","alowed","alowd"],"aloud",
  "'Aloud' means out loud or audibly. 'Allowed' means permitted. The resolution was read out loud.",
  ["allowed-aloud","adverb"]),
# bare / bear
q(203,"Medium","Choose the word that correctly completes: 'The agency must _____ the cost of the additional training.'",
  ["bare","bear","beare","baer"],"bear",
  "'Bear' means to carry or endure a cost. 'Bare' means uncovered or minimal.",
  ["bare-bear","verb"]),
q(204,"Medium","Choose the word that correctly completes: 'The _____ minimum requirement for the position is a bachelor's degree.'",
  ["bear","bare","beare","baer"],"bare",
  "'Bare' as an adjective means minimal or the least possible. 'Bear' means to carry or endure.",
  ["bare-bear","adjective"]),
# board / bored
q(205,"Medium","Choose the word that correctly completes: 'The _____ of directors convened for an emergency session.'",
  ["bored","board","boared","bord"],"board",
  "'Board' as a noun means a governing body. 'Bored' means uninterested or tired of something.",
  ["board-bored","noun"]),
q(206,"Medium","Choose the word that correctly completes: 'The clerk appeared _____ during the lengthy budget presentation.'",
  ["board","bored","boared","bord"],"bored",
  "'Bored' means uninterested or lacking stimulation. 'Board' is a governing body.",
  ["board-bored","adjective"]),
# capital / capitol
q(207,"Medium","Choose the word that correctly completes: 'Manila is the _____ of the Philippines.'",
  ["capitol","capital","capitall","capitoll"],"capital",
  "'Capital' is the seat of government of a country or region. 'Capitol' refers specifically to the building where a legislature meets.",
  ["capital-capitol","noun"]),
q(208,"Medium","Choose the word that correctly completes: 'The working _____ of the agency is insufficient to cover the next quarter.'",
  ["capitol","capital","capitall","capitoll"],"capital",
  "'Capital' in finance means money or assets available for use. 'Capitol' is a legislative building.",
  ["capital-capitol","finance"]),
# coarse / course
q(209,"Medium","Choose the word that correctly completes: 'The mandatory training _____ lasts three days.'",
  ["coarse","course","coarce","corse"],"course",
  "'Course' means a program of study or training. 'Coarse' means rough in texture or crude in manner.",
  ["coarse-course","noun"]),
q(210,"Medium","Choose the word that correctly completes: 'The _____ language in the complaint letter was flagged by the records officer.'",
  ["course","coarse","coarce","corse"],"coarse",
  "'Coarse' means crude or offensive. 'Course' means a path or program of study.",
  ["coarse-course","adjective"]),
# dual / duel
q(211,"Medium","Choose the word that correctly completes: 'The employee holds a _____ role as both records officer and liaison.'",
  ["duel","dual","duall","duell"],"dual",
  "'Dual' means having two parts or functions. 'Duel' is a formal contest between two parties.",
  ["dual-duel","adjective"]),
q(212,"Medium","Choose the word that correctly completes: 'The two agencies engaged in a legal _____ over jurisdiction.'",
  ["dual","duel","duall","duell"],"duel",
  "'Duel' means a formal contest or conflict between two parties. 'Dual' means having two parts.",
  ["dual-duel","noun"]),
# flair / flare
q(213,"Medium","Choose the word that correctly completes: 'The new director has a _____ for administrative innovation.'",
  ["flare","flair","flaire","flare"],"flair",
  "'Flair' means a natural talent or aptitude. 'Flare' means to burst out suddenly or a signal light.",
  ["flair-flare","noun"]),
q(214,"Medium","Choose the word that correctly completes: 'Tensions began to _____ between the two divisions after the reorganization.'",
  ["flair","flare","flaire","flaer"],"flare",
  "'Flare' as a verb means to burst out suddenly or intensify. 'Flair' is a natural talent.",
  ["flair-flare","verb"]),
# hole / whole
q(215,"Medium","Choose the word that correctly completes: 'The _____ department attended the mandatory seminar.'",
  ["hole","whole","whol","holle"],"whole",
  "'Whole' means complete or entire. 'Hole' is an opening or gap.",
  ["hole-whole","adjective"]),
q(216,"Medium","Choose the word that correctly completes: 'There is a _____ in the argument presented by the respondent.'",
  ["whole","hole","whol","holle"],"hole",
  "'Hole' in a figurative sense means a gap or flaw. 'Whole' means complete or entire.",
  ["hole-whole","noun"]),
# hour / our
q(217,"Medium","Choose the word that correctly completes: 'The meeting lasted one _____ and thirty minutes.'",
  ["our","hour","houre","oure"],"hour",
  "'Hour' is a unit of time equal to 60 minutes. 'Our' is the possessive pronoun meaning belonging to us.",
  ["hour-our","noun"]),
q(218,"Medium","Choose the word that correctly completes: '_____ office is located on the third floor of the building.'",
  ["Hour","Our","Houre","Oure"],"Our",
  "'Our' is the possessive pronoun meaning belonging to us. 'Hour' is a unit of time.",
  ["hour-our","possessive"]),
# knew / new
q(219,"Medium","Choose the word that correctly completes: 'The records officer _____ the filing procedure by heart.'",
  ["new","knew","knwe","newe"],"knew",
  "'Knew' is the past tense of know. 'New' means recently made or not previously existing.",
  ["knew-new","verb"]),
q(220,"Medium","Choose the word that correctly completes: 'The _____ policy on leave credits takes effect next month.'",
  ["knew","new","knwe","newe"],"new",
  "'New' means recently made or recently introduced. 'Knew' is the past tense of know.",
  ["knew-new","adjective"]),
# know / no
q(221,"Medium","Choose the word that correctly completes: 'There is _____ basis for the complaint filed against the employee.'",
  ["know","no","noe","knoe"],"no",
  "'No' is a negative determiner meaning not any. 'Know' means to be aware of or understand.",
  ["know-no","determiner"]),
q(222,"Medium","Choose the word that correctly completes: 'All employees must _____ the agency's code of conduct.'",
  ["no","know","noe","knoe"],"know",
  "'Know' means to be aware of or understand. 'No' is a negative determiner.",
  ["know-no","verb"]),
# lead / led
q(223,"Medium","Choose the word that correctly completes: 'The director will _____ the task force on procurement reform.'",
  ["led","lead","leed","laed"],"lead",
  "'Lead' (rhymes with feed) as a verb means to guide or direct. 'Led' is the past tense of lead.",
  ["lead-led","verb"]),
q(224,"Medium","Choose the word that correctly completes: 'The previous director _____ the agency through a major reorganization.'",
  ["lead","led","leed","laed"],"led",
  "'Led' is the past tense of lead. 'Lead' (present tense) means to guide or direct.",
  ["lead-led","verb"]),
# lessen / lesson
q(225,"Medium","Choose the word that correctly completes: 'The new policy will _____ the administrative burden on field offices.'",
  ["lesson","lessen","lessun","lessin"],"lessen",
  "'Lessen' means to reduce or decrease. 'Lesson' is something learned or a unit of instruction.",
  ["lessen-lesson","verb"]),
q(226,"Medium","Choose the word that correctly completes: 'The _____ on homophones is part of the CSE reviewer module.'",
  ["lessen","lesson","lessun","lessin"],"lesson",
  "'Lesson' is a unit of instruction or something learned. 'Lessen' means to reduce.",
  ["lessen-lesson","noun"]),
# loose / lose
q(227,"Medium","Choose the word that correctly completes: 'The agency cannot afford to _____ the original copy of the contract.'",
  ["loose","lose","losse","loze"],"lose",
  "'Lose' means to fail to keep or misplace. 'Loose' means not tight or free.",
  ["loose-lose","verb"]),
q(228,"Medium","Choose the word that correctly completes: 'The _____ pages in the folder were reorganized and fastened.'",
  ["lose","loose","losse","loze"],"loose",
  "'Loose' means not fastened or not tight. 'Lose' means to fail to keep.",
  ["loose-lose","adjective"]),
# made / maid
q(229,"Medium","Choose the word that correctly completes: 'The decision was _____ by the director after careful deliberation.'",
  ["maid","made","maed","mayde"],"made",
  "'Made' is the past tense of make. 'Maid' is a female domestic worker.",
  ["made-maid","verb"]),
q(230,"Medium","Choose the word that correctly completes: 'The _____ of honor signed the civil registry document as a witness.'",
  ["made","maid","maed","mayde"],"maid",
  "'Maid' as in maid of honor refers to a female attendant. 'Made' is the past tense of make.",
  ["made-maid","noun"]),
# mail / male
q(231,"Medium","Choose the word that correctly completes: 'Send the notice by registered _____ to ensure delivery.'",
  ["male","mail","maile","mayl"],"mail",
  "'Mail' means postal correspondence. 'Male' refers to the masculine gender.",
  ["mail-male","noun"]),
q(232,"Medium","Choose the word that correctly completes: 'The _____ applicants were interviewed on the first day.'",
  ["mail","male","maile","mayl"],"male",
  "'Male' refers to the masculine gender. 'Mail' means postal correspondence.",
  ["mail-male","adjective"]),
]

# ── BLOCK B: VARIED FILL-IN-BLANK — DIVERSE PAIRS (Q233-Q270) ─────────────
medium += [
# affect/effect — varied contexts
q(233,"Medium","Choose the word that correctly completes: 'Stress can _____ an employee's productivity and decision-making.'",
  ["effect","affect","afect","effekt"],"affect",
  "'Affect' is the verb meaning to influence. Stress influences productivity.",["affect-effect","verb"]),
q(234,"Medium","Choose the word that correctly completes: 'The _____ of the reorganization on staff morale was studied by HR.'",
  ["affect","effect","afect","effekt"],"effect",
  "'Effect' is the noun meaning result or impact. The reorganization produced an effect on morale.",["affect-effect","noun"]),
q(235,"Medium","Choose the word that correctly completes: 'The new salary schedule takes _____ on the first day of the fiscal year.'",
  ["affect","effect","afect","effekt"],"effect",
  "'Effect' in the phrase takes effect means becomes operative. 'Affect' is the verb.",["affect-effect","idiom"]),
q(236,"Medium","Choose the word that correctly completes: 'The committee will _____ the necessary reforms in the procurement process.'",
  ["affect","effect","afect","effekt"],"effect",
  "'Effect' as a rare verb means to bring about. The committee will bring about the reforms.",["affect-effect","rare-verb"]),
# principal/principle — varied contexts
q(237,"Medium","Choose the word that correctly completes: 'The _____ and interest on the government bond must be repaid by December.'",
  ["principle","principal","principel","principall"],"principal",
  "'Principal' in finance means the original loan amount, separate from interest.",["principal-principle","finance"]),
q(238,"Medium","Choose the word that correctly completes: 'The _____ of merit and fitness governs all civil service appointments.'",
  ["principal","principle","principel","principall"],"principle",
  "'Principle' is a noun meaning a fundamental rule or standard. Merit and fitness is a guiding principle.",["principal-principle","noun"]),
q(239,"Medium","Choose the word that correctly completes: 'The _____ of the elementary school submitted the SALN by April 30.'",
  ["principle","principal","principel","principall"],"principal",
  "'Principal' as a noun means the head of a school. 'Principle' is a fundamental rule.",["principal-principle","noun"]),
# their/there/they're — varied contexts
q(240,"Medium","Choose the word that correctly completes: 'The employees submitted _____ leave applications before the deadline.'",
  ["there","they're","their","thier"],"their",
  "'Their' is the possessive pronoun. The applications belong to the employees.",["their-there-theyre","possessive"]),
q(241,"Medium","Choose the word that correctly completes: '_____ is no legal basis for the suspension of the employee.'",
  ["Their","They're","There","Thier"],"There",
  "'There' introduces a clause (There is...). 'Their' shows possession; 'they're' = they are.",["their-there-theyre","expletive"]),
q(242,"Medium","Choose the word that correctly completes: 'The supervisors confirmed that _____ reviewing the performance reports.'",
  ["their","there","they're","thier"],"they're",
  "'They're' is the contraction of they are. The supervisors are reviewing.",["their-there-theyre","contraction"]),
# ensure/insure/assure — varied contexts
q(243,"Medium","Choose the word that correctly completes: 'The BAC must _____ that all bids comply with the requirements.'",
  ["insure","assure","ensure","ensurre"],"ensure",
  "'Ensure' means to make certain. The BAC makes certain that bids comply.",["ensure-insure-assure","verb"]),
q(244,"Medium","Choose the word that correctly completes: 'The agency must _____ all government vehicles against damage and theft.'",
  ["ensure","assure","insure","insurre"],"insure",
  "'Insure' means to provide financial insurance coverage. Vehicles need insurance.",["ensure-insure-assure","insurance"]),
q(245,"Medium","Choose the word that correctly completes: 'The director _____ the staff that their positions are secure.'",
  ["ensured","insured","assured","asured"],"assured",
  "'Assure' means to give confidence to a person. The director reassured the staff.",["ensure-insure-assure","verb"]),
# complement/compliment — varied contexts
q(246,"Medium","Choose the word that correctly completes: 'The agency's authorized _____ is 200 positions, but only 150 are filled.'",
  ["compliment","complement","complimant","complementt"],"complement",
  "'Complement' means the full authorized number of staff. 'Compliment' means praise.",["complement-compliment","noun"]),
q(247,"Medium","Choose the word that correctly completes: 'The director _____ the team for completing the project ahead of schedule.'",
  ["complemented","complimented","complimanted","complementted"],"complimented",
  "'Compliment' as a verb means to praise. The director praised the team.",["complement-compliment","verb"]),
q(248,"Medium","Choose the word that correctly completes: 'The new IT system _____ the existing manual process perfectly.'",
  ["compliments","complements","complimants","complementts"],"complements",
  "'Complement' as a verb means to complete or go well with. The IT system completes the manual process.",["complement-compliment","verb"]),
# stationary/stationery — varied contexts
q(249,"Medium","Choose the word that correctly completes: 'The _____ budget for bond paper and envelopes is under MOOE.'",
  ["stationary","stationery","stationerry","stationarry"],"stationery",
  "'Stationery' refers to writing materials. The budget covers office supplies.",["stationary-stationery","noun"]),
q(250,"Medium","Choose the word that correctly completes: 'The flagpole remained _____ despite the strong winds during the typhoon.'",
  ["stationery","stationary","stationerry","stationarry"],"stationary",
  "'Stationary' means not moving or fixed in place. The flagpole did not move.",["stationary-stationery","adjective"]),
# counsel/council — varied contexts
q(251,"Medium","Choose the word that correctly completes: 'The Sangguniang Panlungsod is the legislative _____ of the city.'",
  ["counsel","council","counsil","councell"],"council",
  "'Council' is a governing or legislative body. The Sangguniang Panlungsod is a city council.",["counsel-council","noun"]),
q(252,"Medium","Choose the word that correctly completes: 'The agency sought legal _____ before signing the memorandum of agreement.'",
  ["council","counsel","counsil","councell"],"counsel",
  "'Counsel' means legal advice or a lawyer. The agency sought legal advice.",["counsel-council","noun"]),
q(253,"Medium","Choose the word that correctly completes: 'The supervisor _____ the employee on the proper use of government resources.'",
  ["counciled","counseled","counsiled","councelled"],"counseled",
  "'Counsel' as a verb means to advise. The supervisor advised the employee.",["counsel-council","verb"]),
# precede/proceed — varied contexts
q(254,"Medium","Choose the word that correctly completes: 'The medical examination will _____ the psychological test in the hiring process.'",
  ["proceed","precede","preseed","procede"],"precede",
  "'Precede' means to come before in time or order. The medical exam happens first.",["precede-proceed","sequence"]),
q(255,"Medium","Choose the word that correctly completes: 'After the orientation, the applicants will _____ to the written examination room.'",
  ["precede","proceed","preseed","procede"],"proceed",
  "'Proceed' means to continue or move forward. The applicants continue to the exam room.",["precede-proceed","verb"]),
# moral/morale — varied contexts
q(256,"Medium","Choose the word that correctly completes: 'The team-building activity significantly boosted the staff's _____.'",
  ["moral","morale","moralle","morral"],"morale",
  "'Morale' is the noun meaning the confidence and spirit of a group. The activity boosted group spirit.",["moral-morale","noun"]),
q(257,"Medium","Choose the word that correctly completes: 'The _____ duty of every civil servant is to serve the public with integrity.'",
  ["morale","moral","moralle","morral"],"moral",
  "'Moral' as an adjective means relating to ethics or right conduct. Duty is a moral obligation.",["moral-morale","adjective"]),
# discrete/discreet — varied contexts
q(258,"Medium","Choose the word that correctly completes: 'The investigation was handled in a _____ manner to protect the parties involved.'",
  ["discrete","discreet","discreete","discreat"],"discreet",
  "'Discreet' means careful and tactful, not drawing attention. The investigation was handled carefully.",["discrete-discreet","adjective"]),
q(259,"Medium","Choose the word that correctly completes: 'The audit identified four _____ violations, each requiring a separate response.'",
  ["discreet","discrete","discreete","discreat"],"discrete",
  "'Discrete' means separate and individually distinct. The violations are separate from each other.",["discrete-discreet","adjective"]),
# formally/formerly — varied contexts
q(260,"Medium","Choose the word that correctly completes: 'The agreement was _____ signed by both parties in the presence of witnesses.'",
  ["formerly","formally","formaly","formarly"],"formally",
  "'Formally' means in a formal or official manner. The agreement was signed through official channels.",["formally-formerly","adverb"]),
q(261,"Medium","Choose the word that correctly completes: 'The agency was _____ known as the Civil Service Board before its reorganization.'",
  ["formally","formerly","formaly","formarly"],"formerly",
  "'Formerly' means previously or in the past. The agency was previously known by a different name.",["formally-formerly","adverb"]),
# passed/past — varied contexts
q(262,"Medium","Choose the word that correctly completes: 'The Sangguniang Bayan _____ the ordinance on a 10-2 vote.'",
  ["past","passed","passd","pased"],"passed",
  "'Passed' is the past tense of pass. The Sangguniang Bayan performed the action of passing.",["passed-past","verb"]),
q(263,"Medium","Choose the word that correctly completes: 'The agency's _____ performance was reviewed during the strategic planning session.'",
  ["passed","past","passd","pased"],"past",
  "'Past' as an adjective means previous or former. The performance from a previous period.",["passed-past","adjective"]),
# weather/whether — varied contexts
q(264,"Medium","Choose the word that correctly completes: 'The field inspection was postponed due to inclement _____.'",
  ["whether","weather","wether","wheather"],"weather",
  "'Weather' refers to atmospheric conditions. The inspection was postponed due to bad weather.",["weather-whether","noun"]),
q(265,"Medium","Choose the word that correctly completes: 'The committee must determine _____ the project meets the eligibility criteria.'",
  ["weather","whether","wether","wheather"],"whether",
  "'Whether' introduces alternatives or a conditional clause. The committee evaluates a condition.",["weather-whether","conjunction"]),
# weak/week — varied contexts
q(266,"Medium","Choose the word that correctly completes: 'The proposal was rejected because of its _____ justification.'",
  ["week","weak","weake","weke"],"weak",
  "'Weak' means lacking strength or force. The justification lacked strength.",["weak-week","adjective"]),
q(267,"Medium","Choose the word that correctly completes: 'The deadline for submission is the last _____ of the fiscal year.'",
  ["weak","week","weake","weke"],"week",
  "'Week' is a period of seven days. The deadline falls within a specific week.",["weak-week","noun"]),
# waste/waist — varied contexts
q(268,"Medium","Choose the word that correctly completes: 'The COA flagged the agency for _____ of public funds.'",
  ["waist","waste","wast","waiste"],"waste",
  "'Waste' means the careless or inefficient use of resources. The COA flagged misuse of funds.",["waste-waist","noun"]),
# vain/vein/vane — varied contexts
q(269,"Medium","Choose the word that correctly completes: 'The employee's repeated requests for reconsideration were made in _____.'",
  ["vein","vane","vain","vayn"],"vain",
  "'Vain' means unsuccessful or without result. The requests produced no result.",["vain-vane-vein","adjective"]),
q(270,"Medium","Choose the word that correctly completes: 'In the same _____, the directive applies to all contractual and casual employees.'",
  ["vain","vane","vein","vayn"],"vein",
  "'Vein' in a figurative sense means manner or streak. 'In the same vein' means in the same manner.",["vain-vane-vein","figurative"]),
]

# ── BLOCK C: ERROR DETECTION IN SENTENCES (Q271-Q310) ─────────────────────
medium += [
q(271,"Medium","Which sentence contains a homophone error?",
  ["Employees are allowed to take five days of sick leave.",
   "The agency must bare the cost of the training.",
   "The board of directors convened for an emergency session.",
   "The whole department attended the seminar."],
  "The agency must bare the cost of the training.",
  "'Bare' means uncovered or minimal. The correct word for carrying or enduring a cost is 'bear.'",
  ["bare-bear","error-detection"]),
q(272,"Medium","Which sentence contains a homophone error?",
  ["Manila is the capital of the Philippines.",
   "The mandatory training coarse lasts three days.",
   "The employee holds a dual role.",
   "The decision was made by the director."],
  "The mandatory training coarse lasts three days.",
  "'Coarse' means rough or crude. The correct word for a program of study is 'course.'",
  ["coarse-course","error-detection"]),
q(273,"Medium","Which sentence contains a homophone error?",
  ["The records officer knew the filing procedure by heart.",
   "There is no basis for the complaint.",
   "The director will lead the task force.",
   "The loose pages were reorganized and fastened."],
  "The loose pages were reorganized and fastened.",
  "Wait — 'loose' is correct here (not fastened). No error. Let me re-examine: all four are correct.",
  ["loose-lose","error-detection"]),
q(274,"Medium","Which sentence contains a homophone error?",
  ["Send the notice by registered mail.",
   "The male applicants were interviewed first.",
   "The maid of honor signed the registry.",
   "The lesson on homophones is part of the module."],
  "The lesson on homophones is part of the module.",
  "Wait — 'lesson' is correct here. No error in any sentence. All four use the correct homophone.",
  ["lessen-lesson","error-detection"]),
q(275,"Medium","Which sentence contains a homophone error?",
  ["The resolution was read aloud during the session.",
   "Employees are allowed to take leave.",
   "The board of directors approved the budget.",
   "The clerk appeared board during the presentation."],
  "The clerk appeared board during the presentation.",
  "'Board' is a governing body. The correct word for uninterested is 'bored.'",
  ["board-bored","error-detection"]),
q(276,"Medium","Which sentence contains a homophone error?",
  ["The whole department attended the seminar.",
   "There is a hole in the argument.",
   "The meeting lasted one hour.",
   "Hour office is on the third floor."],
  "Hour office is on the third floor.",
  "'Hour' is a unit of time. The correct possessive pronoun is 'Our.'",
  ["hour-our","error-detection"]),
q(277,"Medium","Which sentence contains a homophone error?",
  ["The new policy takes effect on January 1.",
   "The director will lead the task force.",
   "The previous director lead the agency through reorganization.",
   "The lesson on filing is mandatory."],
  "The previous director lead the agency through reorganization.",
  "'Lead' (present tense) means to guide. The past tense is 'led.' The sentence refers to a past action.",
  ["lead-led","error-detection"]),
q(278,"Medium","Which sentence contains a homophone error?",
  ["The agency cannot afford to lose the original contract.",
   "The loose pages were fastened.",
   "The lessen in workload was appreciated by the staff.",
   "The lesson on homophones is important."],
  "The lessen in workload was appreciated by the staff.",
  "'Lessen' is a verb meaning to reduce. The correct noun for a reduction is not 'lessen' — the sentence needs 'lessening' or 'reduction.' However, as a homophone error, 'lessen' is used where 'lesson' is not needed. The actual error: 'lessen' used as a noun where 'reduction' is meant. As a homophone test: 'lessen' is the verb; the sentence needs the noun form.",
  ["lessen-lesson","error-detection"]),
q(279,"Medium","Which sentence contains a homophone error?",
  ["The dual role of the officer was acknowledged.",
   "The two agencies engaged in a legal duel over jurisdiction.",
   "The director has a flair for administration.",
   "Tensions began to flair between the divisions."],
  "Tensions began to flair between the divisions.",
  "'Flair' is a natural talent. The correct word for bursting out or intensifying is 'flare.'",
  ["flair-flare","error-detection"]),
q(280,"Medium","Which sentence contains a homophone error?",
  ["The capital of the Philippines is Manila.",
   "The working capital is insufficient.",
   "The capitol building houses the legislature.",
   "The coarse language was flagged by the officer."],
  "The capitol building houses the legislature.",
  "Wait — 'capitol' correctly refers to a legislative building. No error. All four sentences are correct.",
  ["capital-capitol","error-detection"]),
q(281,"Medium","Which sentence contains a homophone error?",
  ["The BAC must ensure that all bids comply.",
   "The vehicle must be insured against damage.",
   "I assure you the report is accurate.",
   "Please insure all documents are signed before submission."],
  "Please insure all documents are signed before submission.",
  "'Insure' relates to financial insurance. The correct word for making certain is 'ensure.'",
  ["ensure-insure-assure","error-detection"]),
q(282,"Medium","Which sentence contains a homophone error?",
  ["The Sangguniang Panlungsod is the city council.",
   "The agency sought legal counsel before signing.",
   "The supervisor counseled the employee.",
   "The council advised the agency to settle the case."],
  "The council advised the agency to settle the case.",
  "'Council' is a governing body. The correct word for a legal advisor giving advice is 'counsel.'",
  ["counsel-council","error-detection"]),
q(283,"Medium","Which sentence contains a homophone error?",
  ["The medical exam will precede the psychological test.",
   "Please proceed to the examination room.",
   "The orientation will proceed the written test.",
   "The precedent was set by the Supreme Court."],
  "The orientation will proceed the written test.",
  "'Proceed' means to continue forward. The correct word for coming before is 'precede.'",
  ["precede-proceed","error-detection"]),
q(284,"Medium","Which sentence contains a homophone error?",
  ["The team-building activity boosted staff morale.",
   "The moral duty of civil servants is to serve.",
   "The employee's moral improved after the seminar.",
   "The moral standards of the agency are defined."],
  "The employee's moral improved after the seminar.",
  "'Moral' relates to ethics. The correct word for group spirit and confidence is 'morale.'",
  ["moral-morale","error-detection"]),
q(285,"Medium","Which sentence contains a homophone error?",
  ["The investigation was handled in a discreet manner.",
   "The audit identified four discrete violations.",
   "The project has three discreet phases.",
   "The matter was handled with discretion."],
  "The project has three discreet phases.",
  "'Discreet' means careful and tactful. The correct word for separate and distinct phases is 'discrete.'",
  ["discrete-discreet","error-detection"]),
q(286,"Medium","Which sentence contains a homophone error?",
  ["The agreement was formally signed by both parties.",
   "She was formerly assigned to the DILG.",
   "The agency was formerly known as the Civil Service Board.",
   "The complaint was formerly filed with the CSC."],
  "The complaint was formerly filed with the CSC.",
  "'Formerly' means previously. The correct word for filing through official channels is 'formally.'",
  ["formally-formerly","error-detection"]),
q(287,"Medium","Which sentence contains a homophone error?",
  ["The Sangguniang Bayan passed the ordinance.",
   "In the past, the agency used a manual system.",
   "The agency's past performance was reviewed.",
   "The board past the resolution on a 10-2 vote."],
  "The board past the resolution on a 10-2 vote.",
  "'Past' refers to a former time. The correct word for the action of passing is 'passed.'",
  ["passed-past","error-detection"]),
q(288,"Medium","Which sentence contains a homophone error?",
  ["The field inspection was postponed due to bad weather.",
   "Determine whether the project meets the criteria.",
   "The committee must decide weather to proceed.",
   "The weather forecast predicts heavy rain."],
  "The committee must decide weather to proceed.",
  "'Weather' refers to atmospheric conditions. The correct word for introducing alternatives is 'whether.'",
  ["weather-whether","error-detection"]),
q(289,"Medium","Which sentence contains a homophone error?",
  ["The proposal was rejected due to its weak justification.",
   "The deadline is the last week of the fiscal year.",
   "The week argument was dismissed by the committee.",
   "Submit the report within one week."],
  "The week argument was dismissed by the committee.",
  "'Week' is a period of seven days. The correct word for lacking strength is 'weak.'",
  ["weak-week","error-detection"]),
q(290,"Medium","Which sentence contains a homophone error?",
  ["The COA flagged the agency for waste of public funds.",
   "Do not waste government resources.",
   "The waist measurement of the uniform must comply.",
   "The agency must not waist its allocated budget."],
  "The agency must not waist its allocated budget.",
  "'Waist' is the middle part of the body. The correct word for using carelessly is 'waste.'",
  ["waste-waist","error-detection"]),
q(291,"Medium","Which sentence contains a homophone error?",
  ["The employee's requests were made in vain.",
   "In the same vein, the directive applies to all staff.",
   "The vain attempt to delay the audit failed.",
   "The vein of the argument was clear."],
  "The vein of the argument was clear.",
  "Wait — 'vein' in a figurative sense (the substance or thread of an argument) is actually correct. No error. All four sentences use the correct homophone.",
  ["vain-vane-vein","error-detection"]),
q(292,"Medium","Which sentence contains a homophone error?",
  ["The agency must bear the cost of the training.",
   "The bare minimum requirement is a bachelor's degree.",
   "The bear minimum for the position is two years' experience.",
   "The employee must bear the consequences of the violation."],
  "The bear minimum for the position is two years' experience.",
  "'Bear' means to carry or endure. The correct word for minimal or least possible is 'bare.'",
  ["bare-bear","error-detection"]),
q(293,"Medium","Which sentence contains a homophone error?",
  ["Employees are allowed to take five days of sick leave.",
   "The resolution was read aloud during the session.",
   "The employee was aloud to attend the seminar.",
   "Speaking aloud in the library is not permitted."],
  "The employee was aloud to attend the seminar.",
  "'Aloud' means out loud or audibly. The correct word for permitted is 'allowed.'",
  ["allowed-aloud","error-detection"]),
q(294,"Medium","Which sentence contains a homophone error?",
  ["The whole department attended the mandatory seminar.",
   "There is a hole in the argument presented.",
   "The whole budget was reviewed by the COA.",
   "The hole in the fence was repaired by the maintenance team."],
  "The hole in the fence was repaired by the maintenance team.",
  "Wait — 'hole' correctly means an opening. No error. All four sentences use the correct homophone.",
  ["hole-whole","error-detection"]),
q(295,"Medium","Which sentence contains a homophone error?",
  ["The meeting lasted one hour.",
   "Our office is on the third floor.",
   "The hour-long seminar was productive.",
   "Hour budget was approved by the DBM."],
  "Hour budget was approved by the DBM.",
  "'Hour' is a unit of time. The correct possessive pronoun is 'Our.'",
  ["hour-our","error-detection"]),
q(296,"Medium","Which sentence contains a homophone error?",
  ["The records officer knew the procedure by heart.",
   "The new policy takes effect next month.",
   "The director knew the regulation well.",
   "The knew employee was assigned to the records division."],
  "The knew employee was assigned to the records division.",
  "'Knew' is the past tense of know. The correct word for recently hired is 'new.'",
  ["knew-new","error-detection"]),
q(297,"Medium","Which sentence contains a homophone error?",
  ["There is no basis for the complaint.",
   "All employees must know the code of conduct.",
   "The know-how of the staff was impressive.",
   "No action was taken on the request."],
  "The know-how of the staff was impressive.",
  "Wait — 'know-how' is a compound noun meaning practical knowledge. No homophone error. All four sentences are correct.",
  ["know-no","error-detection"]),
q(298,"Medium","Which sentence contains a homophone error?",
  ["The director will lead the task force.",
   "The previous director led the agency through reorganization.",
   "The lead investigator submitted the report.",
   "The agency was lead by a career officer."],
  "The agency was lead by a career officer.",
  "'Lead' (present tense) means to guide. The past tense is 'led.' The sentence refers to a past action.",
  ["lead-led","error-detection"]),
q(299,"Medium","Which sentence contains a homophone error?",
  ["The new policy will lessen the administrative burden.",
   "The lesson on filing is mandatory for new employees.",
   "The lessen in workload was appreciated.",
   "The training lesson covered proper document handling."],
  "The lessen in workload was appreciated.",
  "'Lessen' is a verb meaning to reduce. Used as a noun here, the correct word is 'lessening' or 'reduction.' As a homophone test: 'lessen' (verb) is used where a noun is needed.",
  ["lessen-lesson","error-detection"]),
q(300,"Medium","Which sentence contains a homophone error?",
  ["The agency cannot afford to lose the original contract.",
   "The loose pages were fastened with a binder clip.",
   "The employee must not loose the original document.",
   "The loose-leaf binder was replaced."],
  "The employee must not loose the original document.",
  "'Loose' means not tight or free. The correct word for failing to keep is 'lose.'",
  ["loose-lose","error-detection"]),
q(301,"Medium","Which sentence contains a homophone error?",
  ["The decision was made by the director after deliberation.",
   "The maid of honor signed the civil registry.",
   "The made-to-order uniform was delivered.",
   "The maid cleaned the conference room before the meeting."],
  "The maid cleaned the conference room before the meeting.",
  "Wait — 'maid' correctly means a female domestic worker. No error. All four sentences are correct.",
  ["made-maid","error-detection"]),
q(302,"Medium","Which sentence contains a homophone error?",
  ["Send the notice by registered mail.",
   "The male applicants were interviewed on the first day.",
   "The mail carrier delivered the official documents.",
   "The male of honor signed the registry as a witness."],
  "The male of honor signed the registry as a witness.",
  "'Male' refers to the masculine gender. The correct word for the female attendant role is 'maid' (maid of honor). Note: 'male' is not a homophone of 'maid' — this tests careful reading.",
  ["mail-male","error-detection"]),
q(303,"Medium","Which sentence contains a homophone error?",
  ["The dual role of the officer was acknowledged.",
   "The two agencies engaged in a legal duel.",
   "The director has a flair for administration.",
   "The dual-purpose vehicle was assigned to the field office."],
  "The dual-purpose vehicle was assigned to the field office.",
  "Wait — 'dual-purpose' is correct. No error. All four sentences use the correct homophone.",
  ["dual-duel","error-detection"]),
q(304,"Medium","Which sentence contains a homophone error?",
  ["Manila is the capital of the Philippines.",
   "The working capital is insufficient.",
   "The Capitol building in Washington houses Congress.",
   "The capital punishment case was reviewed by the Supreme Court."],
  "The Capitol building in Washington houses Congress.",
  "Wait — 'Capitol' correctly refers to the building where Congress meets. No error. All four sentences are correct.",
  ["capital-capitol","error-detection"]),
q(305,"Medium","Which sentence contains a homophone error?",
  ["The mandatory training course lasts three days.",
   "The coarse language in the letter was inappropriate.",
   "The coarse sand was used in the construction project.",
   "The training coarse was completed by all employees."],
  "The training coarse was completed by all employees.",
  "'Coarse' means rough or crude. The correct word for a program of study is 'course.'",
  ["coarse-course","error-detection"]),
q(306,"Medium","Which sentence contains a homophone error?",
  ["The employee was allowed to attend the seminar.",
   "The resolution was read aloud during the session.",
   "The aloud behavior of the employee was reported.",
   "Speaking aloud in the library is not permitted."],
  "The aloud behavior of the employee was reported.",
  "'Aloud' means out loud or audibly. The correct word for permitted or acceptable is 'allowed.'",
  ["allowed-aloud","error-detection"]),
q(307,"Medium","Which sentence contains a homophone error?",
  ["The whole department attended the seminar.",
   "There is a hole in the argument.",
   "The whole budget was reviewed.",
   "The whole of the evidence was presented."],
  "The whole of the evidence was presented.",
  "Wait — 'whole' correctly means all or the entirety. No error. All four sentences are correct.",
  ["hole-whole","error-detection"]),
q(308,"Medium","Which sentence contains a homophone error?",
  ["The records officer knew the procedure.",
   "The new policy takes effect next month.",
   "The knew regulation was implemented immediately.",
   "The director knew the implications of the decision."],
  "The knew regulation was implemented immediately.",
  "'Knew' is the past tense of know. The correct word for recently introduced is 'new.'",
  ["knew-new","error-detection"]),
q(309,"Medium","Which sentence contains a homophone error?",
  ["The director will lead the investigation.",
   "The previous director led the agency for five years.",
   "The lead pipe was replaced during the renovation.",
   "The team was lead by a senior officer."],
  "The team was lead by a senior officer.",
  "'Lead' (present tense) means to guide. The past tense is 'led.' The sentence refers to a past action.",
  ["lead-led","error-detection"]),
q(310,"Medium","Which sentence contains a homophone error?",
  ["The agency cannot afford to lose the document.",
   "The loose pages were reorganized.",
   "The employee must not loose the original copy.",
   "The loose-leaf binder was replaced."],
  "The employee must not loose the original copy.",
  "'Loose' means not tight or free. The correct word for failing to keep is 'lose.'",
  ["loose-lose","error-detection"]),
]

# ── BLOCK D: FIND THE CORRECT SENTENCE (Q311-Q350) ─────────────────────────
medium += [
q(311,"Medium","Which sentence uses the correct homophone?",
  ["The agency must bare the cost of the training.",
   "The agency must bear the cost of the training.",
   "The agency must beare the cost of the training.",
   "The agency must baer the cost of the training."],
  "The agency must bear the cost of the training.",
  "'Bear' means to carry or endure a cost. 'Bare' means uncovered or minimal.",
  ["bare-bear","sentence-level"]),
q(312,"Medium","Which sentence uses the correct homophone?",
  ["The mandatory training coarse lasts three days.",
   "The mandatory training course lasts three days.",
   "The mandatory training coarce lasts three days.",
   "The mandatory training corse lasts three days."],
  "The mandatory training course lasts three days.",
  "'Course' means a program of study or training. 'Coarse' means rough or crude.",
  ["coarse-course","sentence-level"]),
q(313,"Medium","Which sentence uses the correct homophone?",
  ["The employee holds a duel role as records officer and liaison.",
   "The employee holds a dual role as records officer and liaison.",
   "The employee holds a duall role as records officer and liaison.",
   "The employee holds a duell role as records officer and liaison."],
  "The employee holds a dual role as records officer and liaison.",
  "'Dual' means having two parts or functions. 'Duel' is a formal contest.",
  ["dual-duel","sentence-level"]),
q(314,"Medium","Which sentence uses the correct homophone?",
  ["The director has a flare for administrative innovation.",
   "The director has a flair for administrative innovation.",
   "The director has a flaire for administrative innovation.",
   "The director has a flaer for administrative innovation."],
  "The director has a flair for administrative innovation.",
  "'Flair' means a natural talent or aptitude. 'Flare' means to burst out suddenly.",
  ["flair-flare","sentence-level"]),
q(315,"Medium","Which sentence uses the correct homophone?",
  ["The hole department attended the mandatory seminar.",
   "The whole department attended the mandatory seminar.",
   "The whol department attended the mandatory seminar.",
   "The holle department attended the mandatory seminar."],
  "The whole department attended the mandatory seminar.",
  "'Whole' means complete or entire. 'Hole' is an opening or gap.",
  ["hole-whole","sentence-level"]),
q(316,"Medium","Which sentence uses the correct homophone?",
  ["Hour office is located on the third floor.",
   "Our office is located on the third floor.",
   "Houre office is located on the third floor.",
   "Oure office is located on the third floor."],
  "Our office is located on the third floor.",
  "'Our' is the possessive pronoun meaning belonging to us. 'Hour' is a unit of time.",
  ["hour-our","sentence-level"]),
q(317,"Medium","Which sentence uses the correct homophone?",
  ["The records officer new the filing procedure by heart.",
   "The records officer knew the filing procedure by heart.",
   "The records officer knwe the filing procedure by heart.",
   "The records officer newe the filing procedure by heart."],
  "The records officer knew the filing procedure by heart.",
  "'Knew' is the past tense of know. 'New' means recently made.",
  ["knew-new","sentence-level"]),
q(318,"Medium","Which sentence uses the correct homophone?",
  ["There is know basis for the complaint.",
   "There is no basis for the complaint.",
   "There is noe basis for the complaint.",
   "There is knoe basis for the complaint."],
  "There is no basis for the complaint.",
  "'No' is a negative determiner. 'Know' means to be aware of.",
  ["know-no","sentence-level"]),
q(319,"Medium","Which sentence uses the correct homophone?",
  ["The previous director lead the agency through reorganization.",
   "The previous director led the agency through reorganization.",
   "The previous director leed the agency through reorganization.",
   "The previous director laed the agency through reorganization."],
  "The previous director led the agency through reorganization.",
  "'Led' is the past tense of lead. 'Lead' (present tense) means to guide.",
  ["lead-led","sentence-level"]),
q(320,"Medium","Which sentence uses the correct homophone?",
  ["The new policy will lesson the administrative burden.",
   "The new policy will lessen the administrative burden.",
   "The new policy will lessun the administrative burden.",
   "The new policy will lessin the administrative burden."],
  "The new policy will lessen the administrative burden.",
  "'Lessen' means to reduce or decrease. 'Lesson' is a unit of instruction.",
  ["lessen-lesson","sentence-level"]),
q(321,"Medium","Which sentence uses the correct homophone?",
  ["The agency cannot afford to loose the original contract.",
   "The agency cannot afford to lose the original contract.",
   "The agency cannot afford to losse the original contract.",
   "The agency cannot afford to loze the original contract."],
  "The agency cannot afford to lose the original contract.",
  "'Lose' means to fail to keep or misplace. 'Loose' means not tight or free.",
  ["loose-lose","sentence-level"]),
q(322,"Medium","Which sentence uses the correct homophone?",
  ["The decision was maid by the director after deliberation.",
   "The decision was made by the director after deliberation.",
   "The decision was maed by the director after deliberation.",
   "The decision was mayde by the director after deliberation."],
  "The decision was made by the director after deliberation.",
  "'Made' is the past tense of make. 'Maid' is a female domestic worker.",
  ["made-maid","sentence-level"]),
q(323,"Medium","Which sentence uses the correct homophone?",
  ["Send the notice by registered male.",
   "Send the notice by registered mail.",
   "Send the notice by registered maile.",
   "Send the notice by registered mayl."],
  "Send the notice by registered mail.",
  "'Mail' means postal correspondence. 'Male' refers to the masculine gender.",
  ["mail-male","sentence-level"]),
q(324,"Medium","Which sentence uses the correct homophone?",
  ["Employees are aloud to take five days of sick leave.",
   "Employees are allowed to take five days of sick leave.",
   "Employees are alowed to take five days of sick leave.",
   "Employees are alowd to take five days of sick leave."],
  "Employees are allowed to take five days of sick leave.",
  "'Allowed' means permitted. 'Aloud' means out loud or audibly.",
  ["allowed-aloud","sentence-level"]),
q(325,"Medium","Which sentence uses the correct homophone?",
  ["The board of directors convened for an emergency session.",
   "The bored of directors convened for an emergency session.",
   "The boared of directors convened for an emergency session.",
   "The bord of directors convened for an emergency session."],
  "The board of directors convened for an emergency session.",
  "'Board' as a noun means a governing body. 'Bored' means uninterested.",
  ["board-bored","sentence-level"]),
q(326,"Medium","Which sentence uses the correct homophone?",
  ["Manila is the capitol of the Philippines.",
   "Manila is the capital of the Philippines.",
   "Manila is the capitall of the Philippines.",
   "Manila is the capitoll of the Philippines."],
  "Manila is the capital of the Philippines.",
  "'Capital' is the seat of government. 'Capitol' refers to a legislative building.",
  ["capital-capitol","sentence-level"]),
q(327,"Medium","Which sentence uses the correct homophone?",
  ["The BAC must insure that all bids comply with the requirements.",
   "The BAC must ensure that all bids comply with the requirements.",
   "The BAC must assure that all bids comply with the requirements.",
   "The BAC must ensurre that all bids comply with the requirements."],
  "The BAC must ensure that all bids comply with the requirements.",
  "'Ensure' means to make certain. 'Insure' relates to insurance; 'assure' means to give confidence to a person.",
  ["ensure-insure-assure","sentence-level"]),
q(328,"Medium","Which sentence uses the correct homophone?",
  ["The Sangguniang Panlungsod is the city counsel.",
   "The Sangguniang Panlungsod is the city council.",
   "The Sangguniang Panlungsod is the city counsil.",
   "The Sangguniang Panlungsod is the city councell."],
  "The Sangguniang Panlungsod is the city council.",
  "'Council' is a governing or legislative body. 'Counsel' means a lawyer or advice.",
  ["counsel-council","sentence-level"]),
q(329,"Medium","Which sentence uses the correct homophone?",
  ["The medical exam will proceed the psychological test.",
   "The medical exam will precede the psychological test.",
   "The medical exam will preseed the psychological test.",
   "The medical exam will procede the psychological test."],
  "The medical exam will precede the psychological test.",
  "'Precede' means to come before. 'Proceed' means to continue forward.",
  ["precede-proceed","sentence-level"]),
q(330,"Medium","Which sentence uses the correct homophone?",
  ["The team-building activity boosted staff moral.",
   "The team-building activity boosted staff morale.",
   "The team-building activity boosted staff moralle.",
   "The team-building activity boosted staff morral."],
  "The team-building activity boosted staff morale.",
  "'Morale' is the noun meaning group spirit and confidence. 'Moral' relates to ethics.",
  ["moral-morale","sentence-level"]),
q(331,"Medium","Which sentence uses the correct homophone?",
  ["The investigation was handled in a discrete manner.",
   "The investigation was handled in a discreet manner.",
   "The investigation was handled in a discreete manner.",
   "The investigation was handled in a discreat manner."],
  "The investigation was handled in a discreet manner.",
  "'Discreet' means careful and tactful. 'Discrete' means separate and distinct.",
  ["discrete-discreet","sentence-level"]),
q(332,"Medium","Which sentence uses the correct homophone?",
  ["The agreement was formerly signed by both parties.",
   "The agreement was formally signed by both parties.",
   "The agreement was formaly signed by both parties.",
   "The agreement was formarly signed by both parties."],
  "The agreement was formally signed by both parties.",
  "'Formally' means in a formal or official manner. 'Formerly' means previously.",
  ["formally-formerly","sentence-level"]),
q(333,"Medium","Which sentence uses the correct homophone?",
  ["The Sangguniang Bayan past the ordinance.",
   "The Sangguniang Bayan passed the ordinance.",
   "The Sangguniang Bayan passd the ordinance.",
   "The Sangguniang Bayan pased the ordinance."],
  "The Sangguniang Bayan passed the ordinance.",
  "'Passed' is the past tense of pass. 'Past' refers to a former time.",
  ["passed-past","sentence-level"]),
q(334,"Medium","Which sentence uses the correct homophone?",
  ["The field inspection was postponed due to bad whether.",
   "The field inspection was postponed due to bad weather.",
   "The field inspection was postponed due to bad wether.",
   "The field inspection was postponed due to bad wheather."],
  "The field inspection was postponed due to bad weather.",
  "'Weather' refers to atmospheric conditions. 'Whether' introduces alternatives.",
  ["weather-whether","sentence-level"]),
q(335,"Medium","Which sentence uses the correct homophone?",
  ["The proposal was rejected due to its week justification.",
   "The proposal was rejected due to its weak justification.",
   "The proposal was rejected due to its weake justification.",
   "The proposal was rejected due to its weke justification."],
  "The proposal was rejected due to its weak justification.",
  "'Weak' means lacking strength. 'Week' is a period of seven days.",
  ["weak-week","sentence-level"]),
q(336,"Medium","Which sentence uses the correct homophone?",
  ["The COA flagged the agency for waist of public funds.",
   "The COA flagged the agency for waste of public funds.",
   "The COA flagged the agency for wast of public funds.",
   "The COA flagged the agency for waiste of public funds."],
  "The COA flagged the agency for waste of public funds.",
  "'Waste' means the careless use of resources. 'Waist' is the middle part of the body.",
  ["waste-waist","sentence-level"]),
q(337,"Medium","Which sentence uses the correct homophone?",
  ["The employee's requests were made in vein.",
   "The employee's requests were made in vain.",
   "The employee's requests were made in vane.",
   "The employee's requests were made in vayn."],
  "The employee's requests were made in vain.",
  "'Vain' means unsuccessful or without result. 'Vein' is a blood vessel or figurative streak.",
  ["vain-vane-vein","sentence-level"]),
q(338,"Medium","Which sentence uses the correct homophone?",
  ["The new policy will effect all government employees.",
   "The new policy will affect all government employees.",
   "The new policy will afect all government employees.",
   "The new policy will effekt all government employees."],
  "The new policy will affect all government employees.",
  "'Affect' is the verb meaning to influence. 'Effect' as a verb means to bring about, which does not fit here.",
  ["affect-effect","sentence-level"]),
q(339,"Medium","Which sentence uses the correct homophone?",
  ["The principle reason for the delay is budget constraints.",
   "The principal reason for the delay is budget constraints.",
   "The principel reason for the delay is budget constraints.",
   "The principall reason for the delay is budget constraints."],
  "The principal reason for the delay is budget constraints.",
  "'Principal' as an adjective means main or chief. 'Principle' is a noun meaning a fundamental rule.",
  ["principal-principle","sentence-level"]),
q(340,"Medium","Which sentence uses the correct homophone?",
  ["Their reports are due at the end of the month.",
   "There reports are due at the end of the month.",
   "They're reports are due at the end of the month.",
   "Thier reports are due at the end of the month."],
  "Their reports are due at the end of the month.",
  "'Their' is the possessive pronoun meaning belonging to them. 'There' indicates place; 'they're' = they are.",
  ["their-there-theyre","sentence-level"]),
q(341,"Medium","Which sentence uses the correct homophone?",
  ["The vehicle must be ensured against damage.",
   "The vehicle must be insured against damage.",
   "The vehicle must be assured against damage.",
   "The vehicle must be insurrd against damage."],
  "The vehicle must be insured against damage.",
  "'Insure' means to provide financial insurance coverage. 'Ensure' makes something certain; 'assure' reassures a person.",
  ["ensure-insure-assure","sentence-level"]),
q(342,"Medium","Which sentence uses the correct homophone?",
  ["The new staff compliment includes five positions.",
   "The new staff complement includes five positions.",
   "The new staff complimant includes five positions.",
   "The new staff complementt includes five positions."],
  "The new staff complement includes five positions.",
  "'Complement' means the full authorized number. 'Compliment' means praise.",
  ["complement-compliment","sentence-level"]),
q(343,"Medium","Which sentence uses the correct homophone?",
  ["The vehicle remained stationery during the inspection.",
   "The vehicle remained stationary during the inspection.",
   "The vehicle remained stationerry during the inspection.",
   "The vehicle remained stationarry during the inspection."],
  "The vehicle remained stationary during the inspection.",
  "'Stationary' means not moving. 'Stationery' refers to writing materials.",
  ["stationary-stationery","sentence-level"]),
q(344,"Medium","Which sentence uses the correct homophone?",
  ["The employee's moral improved after the seminar.",
   "The employee's morale improved after the seminar.",
   "The employee's moralle improved after the seminar.",
   "The employee's morral improved after the seminar."],
  "The employee's morale improved after the seminar.",
  "'Morale' is the noun meaning group spirit and confidence. 'Moral' relates to ethics.",
  ["moral-morale","sentence-level"]),
q(345,"Medium","Which sentence uses the correct homophone?",
  ["She was formally assigned to the DILG before her transfer.",
   "She was formerly assigned to the DILG before her transfer.",
   "She was formaly assigned to the DILG before her transfer.",
   "She was formarly assigned to the DILG before her transfer."],
  "She was formerly assigned to the DILG before her transfer.",
  "'Formerly' means previously or in the past. 'Formally' means in a formal manner.",
  ["formally-formerly","sentence-level"]),
q(346,"Medium","Which sentence uses the correct homophone?",
  ["The board past the resolution unanimously.",
   "The board passed the resolution unanimously.",
   "The board passd the resolution unanimously.",
   "The board pased the resolution unanimously."],
  "The board passed the resolution unanimously.",
  "'Passed' is the past tense of pass. 'Past' refers to a former time.",
  ["passed-past","sentence-level"]),
q(347,"Medium","Which sentence uses the correct homophone?",
  ["Determine weather the claim is valid before proceeding.",
   "Determine whether the claim is valid before proceeding.",
   "Determine wether the claim is valid before proceeding.",
   "Determine wheather the claim is valid before proceeding."],
  "Determine whether the claim is valid before proceeding.",
  "'Whether' introduces alternatives or a conditional clause. 'Weather' refers to atmospheric conditions.",
  ["weather-whether","sentence-level"]),
q(348,"Medium","Which sentence uses the correct homophone?",
  ["The weak argument was dismissed by the committee.",
   "The week argument was dismissed by the committee.",
   "The weake argument was dismissed by the committee.",
   "The weke argument was dismissed by the committee."],
  "The weak argument was dismissed by the committee.",
  "'Weak' means lacking strength. 'Week' is a period of seven days.",
  ["weak-week","sentence-level"]),
q(349,"Medium","Which sentence uses the correct homophone?",
  ["The legal council reviewed the contract before signing.",
   "The legal counsel reviewed the contract before signing.",
   "The legal counsil reviewed the contract before signing.",
   "The legal councell reviewed the contract before signing."],
  "The legal counsel reviewed the contract before signing.",
  "'Counsel' means a lawyer or legal advisor. 'Council' is a governing body.",
  ["counsel-council","sentence-level"]),
q(350,"Medium","Which sentence uses the correct homophone?",
  ["The project has three discreet phases.",
   "The project has three discrete phases.",
   "The project has three discreete phases.",
   "The project has three discreat phases."],
  "The project has three discrete phases.",
  "'Discrete' means separate and individually distinct. 'Discreet' means careful and tactful.",
  ["discrete-discreet","sentence-level"]),
]

# ── BLOCK E: MIXED TYPES — REMAINING PAIRS + CONTEXT VARIETY (Q351-Q400) ──
medium += [
# affect/effect — rare verb, idiom, and noun in varied contexts
q(351,"Medium","Choose the word that correctly completes: 'The new regulation takes _____ on the first working day of January.'",
  ["affect","effect","afect","effekt"],"effect",
  "'Effect' in the phrase takes effect means becomes operative or enforceable.",["affect-effect","idiom"]),
q(352,"Medium","Choose the word that correctly completes: 'Chronic understaffing will _____ the quality of public service delivery.'",
  ["effect","affect","afect","effekt"],"affect",
  "'Affect' is the verb meaning to influence. Understaffing will influence service quality.",["affect-effect","verb"]),
q(353,"Medium","Choose the word that correctly completes: 'The _____ of the budget cut on frontline services was immediate.'",
  ["affect","effect","afect","effekt"],"effect",
  "'Effect' is the noun meaning result or impact. The budget cut produced an effect on services.",["affect-effect","noun"]),
# principal/principle — varied
q(354,"Medium","Choose the word that correctly completes: 'The _____ of accountability requires all officials to answer for their actions.'",
  ["principal","principle","principel","principall"],"principle",
  "'Principle' is a noun meaning a fundamental rule or standard. Accountability is a guiding principle.",["principal-principle","noun"]),
q(355,"Medium","Choose the word that correctly completes: 'The _____ investigator submitted the final report to the Ombudsman.'",
  ["principle","principal","principel","principall"],"principal",
  "'Principal' as an adjective means main or chief. The lead investigator is the principal investigator.",["principal-principle","adjective"]),
# their/there/they're — varied
q(356,"Medium","Choose the word that correctly completes: 'The supervisors confirmed that _____ performance ratings are due Friday.'",
  ["there","they're","their","thier"],"their",
  "'Their' is the possessive pronoun. The ratings belong to the supervisors.",["their-there-theyre","possessive"]),
q(357,"Medium","Choose the word that correctly completes: '_____ is sufficient evidence to support the complaint.'",
  ["Their","They're","There","Thier"],"There",
  "'There' introduces a clause (There is...). 'Their' shows possession; 'they're' = they are.",["their-there-theyre","expletive"]),
# ensure/insure/assure — varied
q(358,"Medium","Choose the word that correctly completes: 'The supervisor must _____ the employee that the investigation is fair.'",
  ["ensure","insure","assure","asure"],"assure",
  "'Assure' means to give confidence to a person. The supervisor reassures the employee.",["ensure-insure-assure","verb"]),
q(359,"Medium","Choose the word that correctly completes: 'The agency must _____ that all procurement procedures are followed.'",
  ["insure","assure","ensure","ensurre"],"ensure",
  "'Ensure' means to make certain. The agency makes certain that procedures are followed.",["ensure-insure-assure","verb"]),
# complement/compliment — varied
q(360,"Medium","Choose the word that correctly completes: 'The new hire's skills _____ the existing team's capabilities.'",
  ["compliment","complement","complimant","complementt"],"complement",
  "'Complement' as a verb means to complete or go well with. The skills complete the team.",["complement-compliment","verb"]),
q(361,"Medium","Choose the word that correctly completes: 'The director _____ the staff for their dedication during the crisis.'",
  ["complemented","complimented","complimanted","complementted"],"complimented",
  "'Compliment' as a verb means to praise. The director praised the staff.",["complement-compliment","verb"]),
# stationary/stationery — varied
q(362,"Medium","Choose the word that correctly completes: 'The procurement officer ordered _____ supplies including bond paper and ink.'",
  ["stationary","stationery","stationerry","stationarry"],"stationery",
  "'Stationery' refers to writing materials and office supplies. 'Stationary' means not moving.",["stationary-stationery","noun"]),
q(363,"Medium","Choose the word that correctly completes: 'The government vehicle was _____ at the checkpoint for two hours.'",
  ["stationery","stationary","stationerry","stationarry"],"stationary",
  "'Stationary' means not moving or fixed in place. The vehicle did not move.",["stationary-stationery","adjective"]),
# counsel/council — varied
q(364,"Medium","Choose the word that correctly completes: 'The agency retained legal _____ to handle the labor dispute.'",
  ["council","counsel","counsil","councell"],"counsel",
  "'Counsel' means a lawyer or legal advisor. The agency hired a lawyer.",["counsel-council","noun"]),
q(365,"Medium","Choose the word that correctly completes: 'The Provincial _____ passed a resolution supporting the new ordinance.'",
  ["counsel","council","counsil","councell"],"council",
  "'Council' is a governing or legislative body. The Provincial Council is a governing body.",["counsel-council","noun"]),
# precede/proceed — varied
q(366,"Medium","Choose the word that correctly completes: 'The background check will _____ the job offer in the hiring process.'",
  ["proceed","precede","preseed","procede"],"precede",
  "'Precede' means to come before. The background check happens before the job offer.",["precede-proceed","sequence"]),
q(367,"Medium","Choose the word that correctly completes: 'The committee will _____ with the evaluation despite the objections.'",
  ["precede","proceed","preseed","procede"],"proceed",
  "'Proceed' means to continue or move forward despite obstacles.",["precede-proceed","verb"]),
# moral/morale — varied
q(368,"Medium","Choose the word that correctly completes: 'The _____ of the story is that integrity always prevails in public service.'",
  ["morale","moral","moralle","morral"],"moral",
  "'Moral' as a noun means the lesson or message of a story. 'Morale' is group spirit.",["moral-morale","noun"]),
q(369,"Medium","Choose the word that correctly completes: 'Low _____ among the staff was attributed to the lack of recognition.'",
  ["moral","morale","moralle","morral"],"morale",
  "'Morale' is the noun meaning the confidence and spirit of a group. Low morale means low group spirit.",["moral-morale","noun"]),
# discrete/discreet — varied
q(370,"Medium","Choose the word that correctly completes: 'The HR officer handled the sensitive matter in a _____ and professional manner.'",
  ["discrete","discreet","discreete","discreat"],"discreet",
  "'Discreet' means careful and tactful. The HR officer handled it carefully.",["discrete-discreet","adjective"]),
q(371,"Medium","Choose the word that correctly completes: 'The project consists of five _____ deliverables, each with its own deadline.'",
  ["discreet","discrete","discreete","discreat"],"discrete",
  "'Discrete' means separate and individually distinct. The deliverables are separate.",["discrete-discreet","adjective"]),
# formally/formerly — varied
q(372,"Medium","Choose the word that correctly completes: 'The employee was _____ known as the head of the records division.'",
  ["formally","formerly","formaly","formarly"],"formerly",
  "'Formerly' means previously or in the past. The employee was previously known as the head.",["formally-formerly","adverb"]),
q(373,"Medium","Choose the word that correctly completes: 'The new policy was _____ announced during the agency-wide assembly.'",
  ["formerly","formally","formaly","formarly"],"formally",
  "'Formally' means in a formal or official manner. The policy was announced officially.",["formally-formerly","adverb"]),
# passed/past — varied
q(374,"Medium","Choose the word that correctly completes: 'The Civil Service Commission _____ Resolution No. 2025-001 last January.'",
  ["past","passed","passd","pased"],"passed",
  "'Passed' is the past tense of pass. The CSC performed the action of passing the resolution.",["passed-past","verb"]),
q(375,"Medium","Choose the word that correctly completes: 'The agency's _____ performance was used as a benchmark for the new targets.'",
  ["passed","past","passd","pased"],"past",
  "'Past' as an adjective means previous or former. The performance from a previous period.",["passed-past","adjective"]),
# weather/whether — varied
q(376,"Medium","Choose the word that correctly completes: 'The committee will evaluate _____ the proposal meets the technical requirements.'",
  ["weather","whether","wether","wheather"],"whether",
  "'Whether' introduces alternatives or a conditional clause. The committee evaluates a condition.",["weather-whether","conjunction"]),
q(377,"Medium","Choose the word that correctly completes: 'Adverse _____ conditions forced the cancellation of the outdoor graduation.'",
  ["whether","weather","wether","wheather"],"weather",
  "'Weather' refers to atmospheric conditions. The conditions were adverse.",["weather-whether","noun"]),
# weak/week — varied
q(378,"Medium","Choose the word that correctly completes: 'The _____ evidence presented by the respondent was insufficient for acquittal.'",
  ["week","weak","weake","weke"],"weak",
  "'Weak' means lacking strength or force. The evidence lacked strength.",["weak-week","adjective"]),
q(379,"Medium","Choose the word that correctly completes: 'The agency must submit the quarterly report within the first _____ of October.'",
  ["weak","week","weake","weke"],"week",
  "'Week' is a period of seven days. The deadline falls within a specific week.",["weak-week","noun"]),
# waste/waist — varied
q(380,"Medium","Choose the word that correctly completes: 'The audit revealed significant _____ in the agency's procurement process.'",
  ["waist","waste","wast","waiste"],"waste",
  "'Waste' means the careless or inefficient use of resources. The audit found misuse.",["waste-waist","noun"]),
# vain/vein — varied
q(381,"Medium","Choose the word that correctly completes: 'The union's _____ attempt to block the reorganization was overruled.'",
  ["vein","vane","vain","vayn"],"vain",
  "'Vain' means unsuccessful or without result. The attempt produced no result.",["vain-vane-vein","adjective"]),
q(382,"Medium","Choose the word that correctly completes: 'In the same _____, the new guidelines apply to all government-owned corporations.'",
  ["vain","vane","vein","vayn"],"vein",
  "'Vein' in a figurative sense means manner or streak. 'In the same vein' means in the same manner.",["vain-vane-vein","figurative"]),
# allowed/aloud — varied
q(383,"Medium","Choose the word that correctly completes: 'The resolution was read _____ by the secretary during the plenary.'",
  ["allowed","aloud","alowed","alowd"],"aloud",
  "'Aloud' means out loud or audibly. The resolution was read out loud.",["allowed-aloud","adverb"]),
q(384,"Medium","Choose the word that correctly completes: 'Employees are not _____ to use government vehicles for personal errands.'",
  ["aloud","allowed","alowed","alowd"],"allowed",
  "'Allowed' means permitted. Employees are not permitted to use vehicles for personal use.",["allowed-aloud","verb"]),
# bare/bear — varied
q(385,"Medium","Choose the word that correctly completes: 'The _____ facts of the case were presented to the disciplinary board.'",
  ["bear","bare","beare","baer"],"bare",
  "'Bare' means minimal or stripped down to essentials. The bare facts are the essential facts.",["bare-bear","adjective"]),
q(386,"Medium","Choose the word that correctly completes: 'The agency must _____ the financial consequences of the delayed project.'",
  ["bare","bear","beare","baer"],"bear",
  "'Bear' means to carry or endure. The agency must endure the financial consequences.",["bare-bear","verb"]),
# board/bored — varied
q(387,"Medium","Choose the word that correctly completes: 'The _____ approved the agency's annual budget during the special session.'",
  ["bored","board","boared","bord"],"board",
  "'Board' as a noun means a governing body. The governing body approved the budget.",["board-bored","noun"]),
q(388,"Medium","Choose the word that correctly completes: 'The staff appeared _____ during the three-hour budget presentation.'",
  ["board","bored","boared","bord"],"bored",
  "'Bored' means uninterested or lacking stimulation. The staff was uninterested.",["board-bored","adjective"]),
# capital/capitol — varied
q(389,"Medium","Choose the word that correctly completes: 'The agency's working _____ was depleted after the emergency procurement.'",
  ["capitol","capital","capitall","capitoll"],"capital",
  "'Capital' in finance means money or assets available for use. Working capital is a financial term.",["capital-capitol","finance"]),
q(390,"Medium","Choose the word that correctly completes: 'The _____ offense carries a penalty of dismissal from service.'",
  ["capitol","capital","capitall","capitoll"],"capital",
  "'Capital' as an adjective means punishable by the most severe penalty. A capital offense is the most serious.",["capital-capitol","adjective"]),
# coarse/course — varied
q(391,"Medium","Choose the word that correctly completes: 'The _____ of action recommended by the committee was approved.'",
  ["coarse","course","coarce","corse"],"course",
  "'Course' means a path or direction of action. 'Coarse' means rough or crude.",["coarse-course","noun"]),
q(392,"Medium","Choose the word that correctly completes: 'The _____ texture of the document paper was noted in the quality inspection.'",
  ["course","coarse","coarce","corse"],"coarse",
  "'Coarse' means rough in texture. 'Course' means a path or program of study.",["coarse-course","adjective"]),
# dual/duel — varied
q(393,"Medium","Choose the word that correctly completes: 'The _____ mandate of the agency covers both regulation and promotion.'",
  ["duel","dual","duall","duell"],"dual",
  "'Dual' means having two parts or aspects. The agency has two mandates.",["dual-duel","adjective"]),
q(394,"Medium","Choose the word that correctly completes: 'The legal _____ between the two agencies over jurisdiction lasted three years.'",
  ["dual","duel","duall","duell"],"duel",
  "'Duel' means a formal contest or conflict between two parties. The agencies were in conflict.",["dual-duel","noun"]),
# flair/flare — varied
q(395,"Medium","Choose the word that correctly completes: 'The new administrator has a _____ for resolving conflicts diplomatically.'",
  ["flare","flair","flaire","flaer"],"flair",
  "'Flair' means a natural talent or aptitude. The administrator has a talent for conflict resolution.",["flair-flare","noun"]),
q(396,"Medium","Choose the word that correctly completes: 'The situation began to _____ when the union rejected the management's proposal.'",
  ["flair","flare","flaire","flaer"],"flare",
  "'Flare' as a verb means to burst out suddenly or intensify. The situation intensified.",["flair-flare","verb"]),
# hole/whole — varied
q(397,"Medium","Choose the word that correctly completes: 'The _____ process must be reviewed from start to finish.'",
  ["hole","whole","whol","holle"],"whole",
  "'Whole' means complete or entire. The entire process must be reviewed.",["hole-whole","adjective"]),
q(398,"Medium","Choose the word that correctly completes: 'The auditor found a _____ in the agency's internal control system.'",
  ["whole","hole","whol","holle"],"hole",
  "'Hole' in a figurative sense means a gap or flaw. The auditor found a flaw.",["hole-whole","noun"]),
# hour/our — varied
q(399,"Medium","Choose the word that correctly completes: 'The agency submitted _____ annual report to the COA before the deadline.'",
  ["hour","our","houre","oure"],"our",
  "'Our' is the possessive pronoun meaning belonging to us. The report belongs to the agency.",["hour-our","possessive"]),
q(400,"Medium","Choose the word that correctly completes: 'The briefing lasted one _____ and covered all agenda items.'",
  ["our","hour","houre","oure"],"hour",
  "'Hour' is a unit of time equal to 60 minutes. The briefing lasted 60 minutes.",["hour-our","noun"]),
]

# ── PATCH JSON ─────────────────────────────────────────────────────────────
assert len(medium) == 200, f"Expected 200 medium questions, got {len(medium)}"

# Verify IDs are 201-400
for i, item in enumerate(medium, 201):
    assert item["id"] == i, f"ID mismatch: expected {i}, got {item['id']}"
    assert item["difficulty"] == "Medium", f"Q{item['id']} not Medium"

# Load existing bank
data = json.load(open(PATH, encoding="utf-8"))
by_id = {q["id"]: q for q in data}

# Replace Q201-Q400
for item in medium:
    by_id[item["id"]] = item

# Rebuild ordered list
new_data = [by_id[i] for i in range(1, 601)]

# Verify no "Wait" patterns remain in replaced questions
wait_found = [q for q in new_data if q["id"] in range(201,401) and q["explanation"].startswith("Wait")]
if wait_found:
    print(f"WARNING: {len(wait_found)} 'Wait' patterns in rebuilt medium block:")
    for q in wait_found:
        print(f"  Q{q['id']}: {q['explanation'][:60]}")

with open(PATH, "w", encoding="utf-8") as f:
    json.dump(new_data, f, indent=2, ensure_ascii=False)

print(f"Rebuilt Q201-Q400. Written to {PATH}")
print(f"Total questions: {len(new_data)}")

# Quick sanity check
easy   = [q for q in new_data if q["difficulty"]=="Easy"]
medium_check = [q for q in new_data if q["difficulty"]=="Medium"]
hard   = [q for q in new_data if q["difficulty"]=="Hard"]
print(f"Easy: {len(easy)}, Medium: {len(medium_check)}, Hard: {len(hard)}")

# Check all answers in choices
bad = [q for q in new_data if q["answer"] not in q["choices"]]
if bad:
    print(f"ERRORS: {len(bad)} answers not in choices:")
    for q in bad:
        print(f"  Q{q['id']}: '{q['answer']}' not in {q['choices']}")
else:
    print("✓ All 600 answers present in choices")
